export const APP_VERSION = '2.1.0';
export const VERSION = '2.1.0';
export const APP_VERSION_DATE = '17/05/2026 12:00';
export const CHANGELOG = [
  '## [V2.1.0] - 17/05/2026 12:00',
  '### Estabilidade & Offline',
  '- **Progresso Offline**: Ao retornar ao jogo, o time continua farmando em background. XP, moedas e materiais são calculados pelo tempo fora (cap: 8h) e exibidos numa tela de boas-vindas.',
  '- **Jogar Offline**: Firestore com persistência local (IndexedDB) — leituras e escritas funcionam sem internet e sincronizam automaticamente ao reconectar.',
  '- **Detecção de Conexão**: Aviso automático ao ficar offline; sync imediato ao reconectar.',
  '- **Save de Emergência**: Ao fechar/minimizar o app, o progresso é salvo instantaneamente no localStorage (com timestamp para o cálculo offline).',
  '- **localStorage Comprimido**: Saves locais agora usam LZString (mesmo sistema do Firestore), eliminando o risco de quota overflow em jogadores avançados.',
  '- **Erros Silenciosos Corrigidos**: Saves automáticos, save de boss e logout agora têm tratamento de erro adequado — o jogador é notificado em caso de falha.',
  '- **Firestore Limpo**: Campo legado `gameState` removido dos documentos via `deleteField()` após migração para `compressedState`.',
  '',
  '## [V2.0.0] - 16/05/2026 17:30',
  '### Visual — Backgrounds Específicos para Todas as Rotas e Batalhas (10 Regiões)',
  '- **200+ Backgrounds Originais**: Criados e integrados cenários únicos para cada rota, ginásio, rival e batalha em todas as 10 regiões (Kanto, Johto, Hoenn, Sinnoh, Unova, Kalos, Alola, Galar, Paldea, Hisui).',
  '- **Kalos Completo**: Azure Bay, Frost Cavern, Snowbelle, Victory Road e Glittering Cave com imagens dedicadas (antes usavam cave/snow genéricos).',
  '- **Alola Completo**: Verdant Cavern, Akala Island, Ulaula Island, Vast Poni Canyon e Mount Lanakila com cenários exclusivos.',
  '- **Galar Completo**: Wild Area, Galar Mine, Hulbury, Circhester e Rose Tower com imagens específicas.',
  '- **Paldea Completo**: Poco Path, Artazon, Medali, Glaseado Mountain e Area Zero com arte dedicada.',
  '- **Kanto Expandido**: 15+ cenários específicos incluindo Rock Tunnel, SS Anne (Navio), Rocket Hideout, Silph Co., Pokémon Tower, Cerulean Cave e Pokémon Mansion.',
  '- **Desafios Corrigidos**: Silph Co. e QG Rocket nos Challenges agora usam suas imagens exclusivas; rematches de ginásio usam bg_kanto_gym.',
  '- **Zero Placeholders**: Eliminado o último uso de `bg_gym_1776863824590` em todos os componentes.',
  '',
  '## [V1.99.0] - 16/05/2026 15:45',
  '### Visual — Standardização Global de Backgrounds e Asset Clean-up',
  '- **Unificação de Nomenclatura**: Todos os caminhos de fundo migrados para o padrão "bg_" unificado (Expedições, Ginásios, Bosses e Raids).',
  '- **Remoção de Timestamps**: Limpeza de nomes de arquivos legados com timestamps (ex: `bg_grass_1776863779024` -> `bg_kanto_grass`).',
  '- **Performance e Confiabilidade**: Implementação do helper `fixBgPath` em todos os componentes de UI para garantir carregamento dinâmico robusto em qualquer ambiente (GitHub Pages/Local).',
  '- **Correção de Batalhas**: Atualização completa do `battleBackgrounds.js` para usar o novo padrão de nomes limpos, eliminando falhas de carregamento em rotas clássicas.',
  '- **Raid Screen Fix**: Corrigido background da Raid que utilizava path quebrado e agora segue o padrão "bg_raid.webp".',
  '',
  '## [V1.98.15] - 16/05/2026 12:34',
  '### Visual — Padronização Global de Backgrounds de Batalha',
  '- **Standardização de Assets**: Migração completa de todos os caminhos legados "battle_bg_" para o novo padrão "bg_", garantindo consistência visual em todo o jogo.',
  '- **Refatoração de Desafios**: Atualizados todos os backgrounds de Ginásios, Rivais e Elite Four no `ChallengesScreen` para o novo sistema de assets HD.',
  '- **Registry de Backgrounds**: Otimização do `battleBackgrounds.js` para suportar fallbacks dinâmicos por região e tipo de terreno.',
  '- **Correção em Kalos**: Verificados e corrigidos backgrounds em rotas de Kalos que estavam utilizando placeholders temporários.',
  '',
  '## [V1.98.13] - 16/05/2026 12:20',
  '### Visual — Overhaul Completo de Backgrounds HD e Fallbacks Regionais',
  '- **Backgrounds Kalos**: Implementação de assets HD para todas as rotas principais (Glittering Cave, Reflection Cave, Azure Bay, Victory Road, etc.).',
  '- **Fallbacks Regionais**: Novo sistema inteligente que atribui backgrounds temáticos automáticos para rotas não mapeadas individualmente em todas as regiões.',
  '- **Arenas de Equipes Vilãs**: Adicionados backgrounds exclusivos de alta fidelidade para confrontos contra Equipes Galactic, Plasma, Flare, Skull, Yell e Star.',
  '- **Sinnoh HD**: Atualização de todos os Ginásios, Liga Pokémon e bases Galácticas com novos assets premium.',
  '- **Fix de Emboscadas**: Corrigido erro que impedia a exibição dos backgrounds temáticos durante encontros aleatórios com vilões.',
  '',
  '## [V1.98.11] - 16/05/2026 10:47',
  '### Correções e Melhorias de Qualidade',
  '- **Sprite de Pokémon Gen 6+**: Pokémon de Gen 6+ (Froakie, Chespin, etc.) não tentam mais GIF animado Gen 5 inexistente — vão direto ao PNG correto, sem flash de imagem quebrada.',
  '- **Iniciais em rotas**: Kalos, Alola, Galar e Paldea agora liberam iniciais apenas após derrota do rival (padrão das demais regiões).',
  '- **Z-index nav bar**: Barra de navegação não aparece mais sobre modais.',
  '- **Console limpo**: Removidos todos os console.log de debug em produção.',
  '- **Paths do bg_lab**: Background de laboratório usa path relativo correto em todos os 10 locais.',
  '',
  '## [V1.98.10] - 16/05/2026 10:04',
  '### Correção — Background de Laboratório em Produção',
  '- **Todos os modais e telas de intro**: Background de lab agora usa path relativo correto para GitHub Pages (base ./). Todos os 10 usos corrigidos.',
  '',
  '## [V1.98.9] - 16/05/2026 10:04',
  '### Correção Crítica — Crash ao Abrir Modal de Kalos',
  '- **React is not defined**: Corrigido erro que causava tela azul ao clicar em "Conhecer Nova Região".',
  '- **Ícones 404**: Corrigidos ícones quebrados nos cards de Região Customizada e Kalos (URLs inválidos substituídos).',
  '',
  '## [V1.98.8] - 16/05/2026 09:25',
  '### Feature — Preview de Pokémon Inicial antes da Escolha',
  '- **Todas as 9 regiões**: Clicar em um inicial abre um modal de detalhes com artwork oficial, tipos, stats base e golpes iniciais.',
  '- **Confirmação segura**: O modal tem botão "Escolher [nome]!" e "Escolher outro", evitando seleções acidentais.',
  '',
  '## [V1.98.7] - 16/05/2026 10:30',
  '### Visual — Lab Background em Todas as Telas de Introdução Regional',
  '- **Todas as 9 regiões** (Johto, Hoenn, Sinnoh, Unova, Kalos, Alola, Galar, Hisui, Paldea) agora exibem o background de laboratório na tela de boas-vindas/escolha de inicial, com gradiente da cor regional sobreposto.',
  '',
  '## [V1.98.6] - 16/05/2026 10:00',
  '### Visual — Background de Laboratório nos Modais de Professores',
  '- **Todos os modais de professor** (Carvalho, Elm, Birch, Rowan, Juniper, Sycamore, Kukui, Magnólia, Laventon, Sada) agora exibem o background de laboratório na faixa do cabeçalho, com gradiente da cor da região sobreposto.',
  '- **Tela de Introdução Regional** (RegionIntroScreen) também recebe o laboratório como textura sutil de fundo, atrás do sprite do professor.',
  '',
  '## [V1.98.5] - 16/05/2026 09:30',
  '### Correção — Sprites dos Professores nos Modais Regionais',
  '- **Sprites corretos**: Todos os modais de boas-vindas regionais agora exibem o sprite correto do professor (Elm, Birch, Rowan, Juniper, Sycamore, Kukui, Magnólia, Sada). Os nomes de sprite no PokémonShowdown não usam o prefixo "professor".',
  '',
  '## [V1.98.4] - 16/05/2026 09:00',
  '### Correção — Modal de Convite Regional (Unova → Kalos)',
  '- **Auditoria corrigida**: Ao remover um "Ghost Champion", a flag `_modal_shown` correspondente também é removida, permitindo que o modal reapareça quando o jogador vencer novamente.',
  '- **Card de fallback na Cidade**: O card "Conhecer Nova Região" reabre o modal de convite do Prof. Sycamore (em vez de ir direto para a seleção de inicial), dando a experiência completa ao jogador.',
  '',
  '## [V1.98.3] - 15/05/2026 22:15',
  '### Auditoria — Troféus de Campeão e Status Regional',
  '- **Fim dos "Ghost Champions"**: Implementado sistema de auditoria que limpa troféus de jogadores que possuíam a flag de campeão mas não tinham a última insígnia da região (resolvendo bugs de flags poluidas por encontros randômicos).',
  '- **Hardening de Batalha**: O status de Campeão Regional agora só é concedido se o jogador derrotar o Boss da Liga na tela de Desafios. Encontros "selvagens" com o Campeão em rotas não concedem mais o título.',
  '- **Rastreamento Robustecido**: Todas as batalhas de desafio (Rivais, Vilões, Elite Four) agora atualizam corretamente o contador `gymDefeatCounts`, permitindo uma verificação secundária de conquistas.',
  '- **Trainer Card Verificado**: O card de treinador agora valida o status de campeão cruzando as worldFlags com o histórico de vitórias e a progressão regional real.',
  '',
  '## [V1.98.1] - 15/05/2026 21:51',
  '### Melhorado — Efeitos Visuais de Batalha',
  '- **Reação de Dano Suavizada**: O efeito de "piscar" (flicker) ao receber dano foi suavizado e encurtado, reduzindo o cansaço visual sem perder o feedback de impacto.',
  '- **Overlays Elementais Dinâmicos**: Adicionada inteligência visual que sobrepõe efeitos de fogo, raio, água e gelo em todos os golpes dos respectivos tipos, mesmo para ataques genéricos.',
  '',
  '## [V1.98.0] - 15/05/2026 21:47',
  '### Hardening — Progressão Regional e Lendários',
  '- **Fim dos Unlocks Passivos**: Removidas todas as travas de "unlocks" automáticas das rotas de liga (Unova, Kalos, Alola). Agora, o título de Campeão e o acesso ao pós-jogo são estritamente amarrados à vitória em batalha contra o Campeão.',
  '- **Gatilho de Lendários**: Implementada trava global para Lendários e Míticos. Eles agora só aparecem nas rotas após serem derrotados como bosses em desafios. Taxa de encontro extremamente rara fixada em 0.05% (1 em 2000).',
  '- **Reparo de Sprites Mega**: Corrigida falha visual de Mega Evoluções no BattleScreen e PokemonManagement. Implementado fallback inteligente para sprites de "back" (costas) e suporte total a Mega Evoluções de Gen 6+ que não possuem arte animada no estilo Gen 5.',
  '- **Distribuição Johto**: Raikou, Entei, Suicune, Lugia, Ho-Oh e Celebi agora habitam rotas temáticas de Johto como encontros raros pós-vitória.',
  '',
  '## [V1.97.4] - 15/05/2026 21:15',
  '### Corrigido — Engine de Renderização de Sprites Mega',
  '- **Fallback Multi-nível**: Implementado sistema de recuperação de imagem em 3 estágios (GIF Animado → PNG Estático → Sprite Base). Isso resolve o problema de imagens quebradas para Mega Evoluções customizadas (ex: Mega Emboar #20500) e oficiais com falha na PokeAPI.',
  '- **Correção de UI**: Aplicado fallback em todas as telas: Team List, PC Storage, Pokémon Details Modal, Battle Screen e Mega Evolution Preview.',
  '- **Consistência do PC**: Pokémon Mega Evoluídos agora exibem corretamente sua forma Mega no armazenamento do PC (antes mostravam a forma base).',
  '- **Auditoria de Backgrounds**: Finalizada a padronização das arenas de Unova. Primeiros 4 ginásios com arte exclusiva, outros 4 com mapeamento temático otimizado.',
  '',
  '## [V1.97.3] - 16/05/2026 00:20',
  '### Adicionado — Auditoria e Limpeza de Backgrounds (Unova a Paldea)',
  '- **Correção de Paths**: Substituídos caminhos temporários (`_temp.png`) pelos assets finais (`.webp`) em Kalos e Galar.',
  '- **Arenas Temáticas Alola**: Implementado `gymBgs` para Alola, mapeando o Vulcão Wela e arenas de expedição para os Capitães.',
  '- **Arenas Temáticas Paldea**: Mapeamento completo dos ginásios de Paldea usando o Deserto de Asado e templos de expedição, eliminando o uso da arena da Liga como placeholder.',
  '- **Rotas de Dex Coverage**: Todas as rotas de "Habitat Regional" (Kanto a Hisui) auditadas para usar os melhores backgrounds temáticos disponíveis.',
  '- **Hisui Coverage**: Adicionada a cobertura de Dex para Hisui no sistema de rotas globais.',
  '',
  '## [V1.97.2] - 15/05/2026 21:00',
  '### Adicionado — Overhaul de Arenas (Mapeamento Completo)',
  '- **Mapeamento Regional**: Todas as regiões (Unova a Paldea) agora possuem arenas temáticas para cada líder.',
  '- **Unova Premium**: Primeiros 4 ginásios de Unova com backgrounds exclusivos de alta fidelidade.',
  '- **Engine de Combate**: Finalização da engine de golpes compostos com overlays elementais.',
  '',
  '## [V1.97.0] - 16/05/2026 00:00',
  '### Adicionado — Overhaul Visual de Batalha (Fase 2)',
  '- **Golpes Compostos**: Mordidas, Socos e Chutes agora possuem efeitos elementais sobrepostos (Ex: Thunder Fang exibe mordida + raios).',
  '- **Backgrounds Únicos**: Iniciada a implementação de cenários únicos para cada ginásio de Unova e Kalos, respeitando a temática individual de cada líder.',
  '- **Arena de Liga Premium**: Nova arena oficial para batalhas de campeonato, substituindo placeholders genéricos.',
  '',
  '## [V1.96.0] - 16/05/2026 03:30',
  '### Corrigido',
  '- **ReferenceError: customLevel** no RegionBuilderScreen corrigido (variável renomeada para `defaultLevel`).',
  '- **Modais de Natureza e Habilidade** agora aparecem centralizados na tela (era `items-end`, corrigido para `items-center`).',
  '- **Iniciais por região** — Kalos/Alola/Galar/Paldea agora liberam seus iniciais somente após limpar a primeira rota (rival derrotado). Unova revertida para usar o sistema `addSafe` existente.',
  '- **Modal de recompensas de Raid** — cada item pode ser clicado para abrir detalhes (nome + descrição do item).',
  '- **MoveAnimationLayer** — brace redundante removido que causava falha no build.',
  '',
  '## [V1.95.0] - 16/05/2026 02:00',
  '### Melhorado — Modal do Pokémon da Equipe',
  '- **Item Segurado redesenhado**: exibe o item equipado (ícone + nome + efeito) ou placeholder "Sem item segurado". Toque abre/fecha o seletor de itens da mochila com quantidade disponível. Após equipar, o picker fecha automaticamente.',
  '- **Navegação entre membros da equipe**: setas ‹ › no cabeçalho do modal permitem navegar entre os Pokémon da equipe sem fechar o painel. Indicadores de ponto mostram a posição atual.',
  '- **Sprite mega-evolução corrigido**: cards da equipe e cabeçalho do modal agora exibem o sprite correto do Mega Pokémon (forma alternativa) em vez da forma base.',
  '',
  '## [V1.94.0] - 16/05/2026 00:30',
  '### Adicionado',
  '- **Pokédex — Onde Encontrar**: ao clicar em qualquer Pokémon na Pokédex, o modal exibe a lista de todas as rotas onde aquele Pokémon pode ser encontrado como inimigo selvagem, com nível e região de cada rota.',
  '- **Pokédex — Ir à Rota**: rotas desbloqueadas têm o botão "Ir à rota" que fecha o modal e navega diretamente para a rota na tela de batalha. Rotas bloqueadas exibem badge "🔒 Bloqueada".',
  '- **Fantasmas acumulam a cada derrota**: a tela de derrota agora mostra 1 fantasma a mais a cada vez que o time todo desmaia no mesmo dia (começa em 2: Gastly + Haunter; vai adicionando Gengar, Misdreavus, Shuppet, Banette, Duskull, Sableye, Litwick, Chandelure). Reseta automaticamente no dia seguinte.',
  '- **Contador de derrotas diárias**: a partir da 2ª derrota do dia, aparece um badge discreto "Xª derrota hoje" no canto da tela de derrota.',
  '',
  '## [V1.93.1] - 15/05/2026 23:59',
  '### Corrigido — Auditoria de Rotas',
  '- **Pré-evoluções adicionadas**: Trubbish (#568) em Unova Rota 3; Tynamo (#601) em Chargestone Cave; Golett (#622) e Larvesta (#636) em Unova Rota 9; Aron (#304) em Glittering Cave; Timburr (#532), Deino (#633) e Goomy (#704) em Frost Cavern; Zigzagoon-G (#263) na Wild Area de Galar; Finneon (#456) na Costa Cobalto de Hisui.',
  '- **Lendários gateados**: Cobalion/Terrakion/Virizion (Unova League), Xerneas/Yveltal/Zygarde (Kalos League), Calyrex/Glastrier/Spectrier/Regieleki/Regidrago (Crown Tundra), Koraidon/Miraidon/Terapagos (Paldea Pós-Liga), Uxie/Mesprit/Azelf/Giratina/Arceus (Praça Sagrada Hisui) e Heatran (Stark Mountain) agora exigem flag de progresso para aparecer.',
  '- **Kyurem gateado**: Kyurem (#646) no Giant Chasm agora requer `unova_champion`.',
  '- **Sprite Colress corrigido**: substituído `S.scientist` (indefinido) por `S.gentleman`.',
  '- **Duplicate paldea_area_zero removido**: segunda definição conflitante eliminada; rota unificada com requisito correto (`paldea_champion`) e drops detalhados.',
  '- **Backgrounds atualizados**: Pinwheel Forest, Desert Resort, Chargestone Cave, Twist Mountain (Unova); Santalune Forest, Azure Bay, Frost Cavern, Snowbelle (Kalos); Wela Volcano, Aether Paradise (Alola); Glimwood Tangle, Crown Tundra (Galar); Asado Desert (Paldea); Praça Sagrada (Hisui) — todos com imagens dedicadas.',
  '',
  '## [V1.93.0] - 15/05/2026 23:30',
  '### Adicionado — Região Hisui (10ª região)',
  '- **Hisui desbloqueado**: ao conquistar Paldea, o Prof. Laventon convida o jogador para a terra ancestral de Sinnoh.',
  '- **Iniciais de Hisui**: escolha entre Rowlet (#722), Cyndaquil (#155) ou Oshawott (#501) na tela de intro.',
  '- **8 Rotas de Hisui**: Jubilife (cidade), Campos Obsidiana (×2), Pântano Crimsonite, Litoral das Coberturas, Highlands Coronet, Terras de Gelo, Praça Sagrada.',
  '- **8 Nobres Frenéticos como Líderes**: Mai (Bug), Lian (Grass), Iscan (Fire), Ingo (Electric), Gaeric (Ice), Irida (Water), Volo (Ghost), Kamado (Normal).',
  '- **Liga Hisui**: 5 membros — Cogita, Cyllene, Adaman, Sabi e Kamado (Campeão).',
  '- **Rivais Akari**: 7 batalhas ao longo da jornada em Hisui.',
  '- **Vilões — Recrutas Galácticos e Volo**: 7 batalhas culminando em Volo na Praça Sagrada.',
  '- **Stamps de Hisui**: 8 insígnias únicas (stamps) no painel de Ginásios.',
  '- **Modal de recuperação**: jogadores com Paldea já conquistada veem o convite do Prof. Laventon ao abrir o jogo.',
  '',
  '## [V1.92.5] - 15/05/2026 22:30',
  '### Corrigido',
  '- **Elementos fora da janela de jogo**: botão de RAID, aviso de RAID, modais de Alfa, Receita, edifícios e overlays de carregamento agora usam `position: absolute` em vez de `fixed`, ficando sempre dentro da janela do jogo (max-width 430px).',
  '- **`position: fixed` removido do AppRoot**: todos os elementos flutuantes do jogo passaram de `fixed` para `absolute`, respeitando o container `.app-shell` como âncora de posicionamento.',
  '',
  '## [V1.92.4] - 15/05/2026 22:00',
  '### Corrigido',
  '- **Iniciais de Unova — Anúncio da Prof. Juniper**: após derrotar o rival Cheren na Nuvema Town, a Profa. Juniper aparece com uma tela de anúncio (idêntica ao padrão do Prof. Carvalho em Kanto) informando que Snivy, Tepig e Oshawott foram avistados nas rotas iniciais de Unova.',
  '- **Iniciais de Unova nas Rotas**: Snivy (#495) e Tepig (#498) agora aparecem na Rota 1 de Unova, e Oshawott (#501) na Rota 2, após a flag `unova_rival_1_defeated` ser registrada.',
  '- **Padrão Consistente**: o fluxo de desbloqueio de iniciais de Unova agora segue exatamente o mesmo padrão de Kanto (rival → anúncio da professora → iniciais nas rotas).',
  '',
  '## [V1.92.3] - 15/05/2026 19:30',
  '### Adicionado',
  '- **Pokémon ALFA em Raids**: 5% de chance de encontrar um Pokémon Alfa em qualquer raid.',
  '- **Visual ALFA**: Pokémon Alfa aparecem maiores (130% do tamanho), com aura vermelha pulsante e badge "ALFA" no nome.',
  '- **Visual ALFA + SHINY**: Aura dourada-vermelha especial para Pokémon que são simultaneamente Alfa e Shiny.',
  '- **Bônus de Stats ALFA**: Pokémon Alfa capturados têm ×1.3 em todos os stats. Se também forem Shiny, ×1.5.',
  '- **HP de Raid ALFA**: Raids com Pokémon Alfa têm HP 1.5× maior que o normal.',
  '- **Substituição Automática**: Capturar um Alfa substitui automaticamente a versão normal (não-shiny) na equipe/PC.',
  '- **Diálogo de Confirmação**: Se o jogador já tem um Shiny da mesma espécie, aparece modal perguntando se deseja substituir ou manter os dois.',
  '',
  '## [V1.92.2] - 15/05/2026 17:59',
  '### Adicionado',
  '- **Auto-Buff**: Nova seção no Painel Automático com 4 itens de buff configuráveis individualmente (X-Ataque, X-Defesa, X-Speed, Dire Hit).',
  '- **Efeitos Reais de Buff**: X-Ataque/Defesa/Speed agora aplicam +1 estágio no stat correspondente do Pokémon ativo ao serem usados.',
  '- **Dire Hit**: Ativa efeito temporário de boost de crítico por 5 minutos via sistema de activeEffects (aparece na barra de efeitos ativos).',
  '- **Auto-Buff Automático**: Quando ativado, aplica itens configurados no início de cada novo inimigo. Limitado a stage +1 por batalha para evitar acúmulo excessivo.',
  '### Melhorado',
  '- **Painel Automático — Redesign Completo**: Interface completamente reimaginada com 4 seções distintas (Captura, Poção, Stamina, Buff), cada uma com cor temática e estado visual ativo/inativo.',
  '- **AUTO Button — Badge de Contagem**: O botão AUTO na barra de status agora exibe um badge verde com o número de automações ativas (ex: ●3).',
  '- **Auto-Poção — Estoque em Tempo Real**: Exibe contagem de Poções e Super Poções disponíveis diretamente no painel. Avisa quando estoque está vazio.',
  '- **Auto-Stamina — Lista de Alimentos**: Mostra todos os alimentos disponíveis no inventário em ordem de prioridade de uso (①  item prioritário destacado).',
  '- **Auto-Buff — Cards Interativos**: Cada item de buff tem card próprio com nome, efeito, estoque e indicador ✓ quando ativo. Cards acinzentados quando sem estoque.',
  '- **Resumo de Autos Ativos**: Footer do painel exibe chips coloridos de cada automação ligada.',
  '',
  '## [V1.92.1] - 15/05/2026 18:00',
  '### Corrigido',
  '- **Professores Regionais**: Cada região agora exibe o sprite correto do seu professor.',
  '  - Johto → Prof. Vidoeiro | Hoenn → Prof. Bétula | Sinnoh → Prof. Sorbus',
  '  - Kalos → Prof. Plátano | Galar → Profa. Magnólia | Paldea → Profa. Sada',
  '- **Kanto Inicial**: Prof. Carvalho agora aparece na tela de seleção do starter com fala de boas-vindas.',
  '- **Nomes em Português**: Professores usam nomes localizados para o português brasileiro.',
  '- **Fallback de Sprite Duplo**: Tenta nome alternativo no Showdown antes de recorrer ao Prof. Carvalho.',
  '',
  '## [V1.92.0] - 15/05/2026 15:02',
  '### Adicionado',
  '- **Upgrade Visual "Minha Região"**: Cards de Ginásio e Elite reformulados com estética de alta fidelidade (Hall da Fama).',
  '- **Team Grid Dinâmico**: Visualização da equipe completa com sprites da PokeAPI e badges de nível integrados nos cards.',
  '- **Ajuste de Dificuldade**: Novo Slider de Nível no editor de slots para personalização total do desafio regional.',
  '- **Estética Elemental**: Adicionado brilho suave e ícones de tipo com destaque visual nos cards de ginásio.',
  '- **Persistência de Dados**: Níveis customizados e configurações de slot agora persistem corretamente via Firebase.',
  '',
  '## [V1.90.9] - 15/05/2026 22:45',
  '## [V1.90.8] - 15/05/2026 21:30',
  '## [V1.90.7] - 15/05/2026 21:00',
  '### Alterado',
  '- **Refatoração de Rotas (Unova a Paldea)**: Substituição da geração procedural por definições manuais e precisas baseadas nos jogos oficiais.',
  '- **Redistribuição de Pokémon**: Pokémon selvagens e treinadores redistribuídos para seguir o tema regional e a dificuldade canônica (Lv 5-80).',
  '- **Novos Iniciais Raros**: Iniciais de Unova a Paldea agora podem ser encontrados raramente (~1%) nas rotas iniciais das suas respectivas regiões após derrotar o primeiro rival.',
  '- **Novas Áreas**: Adicionadas áreas icônicas como Dragonspiral Tower (Unova), Reflection Cave (Kalos), Aether Paradise (Alola), Lakeside Route 2 (Galar) e Deserto de Asado (Paldea).',
  '### Corrigido',
  '- **Compatibilidade PC**: Verificada e confirmada a compatibilidade total das gerações 5 a 9 com o sistema de gerenciamento do PC e filtragem regional.',
  '',
  '## [V1.90.6] - 15/05/2026 19:00',
  '### Adicionado',
  '- **Rivais e Vilões expandidos (7 cada)**: todas as 5 regiões futuras (Unova, Kalos, Alola, Galar, Paldea) agora têm 7 batalhas de rival e 7 encontros de equipe vilã com equipes temáticas e progressão adequada.',
  '- **Alola — Capitães de Prova e Kahunas**: líderes de Alola agora são corretamente rotulados como Capitão de Prova (Ilima, Lana, Kiawe, Mallow, Sophocles, Mina) e Grande Julgamento Kahuna (Hala, Olivia, Nanu, Hapu).',
  '- **Paldea — Titãs (Caminho das Lendas)**: 6 titãs adicionados (Klawf, Bombirdier, Orthworm, Presas Gigantes, Dondozo, Falso Dragão) com categoria "titan" e equipes únicas.',
  '- **Paldea — Team Star (Rua Estelar)**: 7 batalhas da Team Star incluindo Giacomo, Mela, Atticus, Ortega, Eri e Penny/Cassiopeia como chefe final.',
  '- **Rotas — Filtro por região expandido**: TravelScreen agora filtra rotas por região ativa para todas as 9 regiões (antes limitado a Kanto/Johto/Hoenn/Sinnoh).',
  '## [V1.90.5] - 15/05/2026 18:00',
  '### Performance',
  '- **Imagens WebP**: 221 backgrounds e ícones convertidos de PNG para WebP (qualidade 82) — 760 MB de assets eliminados.',
  '  - Carregamento inicial até 5× mais rápido em conexões lentas.',
  '  - Service Worker atualizado para cache-first em .webp e versão dinâmica via version.json.',
  '  - Compatibilidade: WebP suportado por 97%+ dos browsers modernos (Chrome, Firefox, Safari 14+, Edge).',
  '## [V1.90.4] - 15/05/2026 15:00',
  '### Balanceamento',
  '- **GYM_LEVEL_CAPS — cap 100 após o 8º ginásio em todas as regiões**: após obter as 8 insígnias o jogador pode treinar até o nível 100 livremente antes de enfrentar a Liga.',
  '  - Kanto champion 65→100 | Johto 65→100 | Hoenn 62→100 | Sinnoh 76→100',
  '  - Unova 84→100 | Kalos 88→100 | Galar 92→100 | Paldea 90→100 | Alola já era 100.',
  '- **Kanto — Sabrina corrigida**: marsh_badge cap 43→46 para corresponder ao nível 46 da Sabrina (antes o cap ficava preso em 43 ao ter 5 insígnias).',
  '## [V1.90.3] - 15/05/2026 14:00',
  '### Corrigido (Crítico)',
  '- **Bug de cap de nível em Unova/Kalos/Alola/Galar/Paldea**: validateTeamAccess não contabilizava insígnias dessas regiões, travando o nível máximo em 14 para jogadores ainda não Campeões. Corrigido adicionando filtragem correta de insígnias para todas as 9 regiões.',
  '### Balanceamento',
  '- **GYM_LEVEL_CAPS — Regiões pós-Sinnoh corrigidas**: campeões estavam todos com cap 100, permitindo times muito superiores aos campeões.',
  '  - Hoenn champion: 70 → 62 (Steven máx. 62)',
  '  - Unova último ginásio: 60 → 64 | champion: 100 → 84 (Alder máx. 82)',
  '  - Kalos último ginásio: 65 → 68 | champion: 100 → 88 (Diantha máx. 86)',
  '  - Alola elite_stamp: 65 → 76 | champion_stamp: 75 → 90 | ultra: 85 → 95 | champion: 100 → 100',
  '  - Galar último ginásio: 55 → 60 | champion: 100 → 92 (Leon máx. 90)',
  '  - Paldea último ginásio: 60 → 62 | champion: 100 → 90 (Geeta máx. 88)',
  '- **Hoenn — Steven (Campeão) nivelado**: equipe elevada de 55–58 para 57–62 para ser compatível com o novo cap de 62.',
  '## [V1.90.2] - 15/05/2026 12:00',
  '### Balanceamento',
  '- **Sinnoh — Progressão corrigida**: níveis de todos os ginásios e Elite Four drasticamente reduzidos para serem coerentes com os jogos originais e com outras regiões.',
  '  - Candice (7º): 62-66 → 47-51 | Volkner (8º): 72-76 → 54-58',
  '  - Aaron (Elite 1): 82-85 → 60-63 | Bertha: 84-87 → 62-65 | Flint: 86-89 → 64-67',
  '  - Lucian: 88-91 → 66-70 | Cynthia (Campeã): 92-96 → 70-74',
  '- **Sinnoh — GYM_LEVEL_CAPS ajustados**: caps de treinamento agora escalam suavemente de 14 a 76 (era 16 a 100). Exemplo: após 6 badges cap era 66 → agora 51.',
  '- **Encontros em rotas — Filtro de evolução automático**: rotas de nível alto agora exibem formas evoluídas dos Pokémon. Caterpie/Weedle/Pidgey/Magikarp e mais de 100 espécies evoluem automaticamente com base no nível da rota.',
  '  - Ex.: rota normalizada para nível 50 mostra Pidgeot (não Pidgey), Tentacruel (não Tentacool), Luxray (não Shinx).',
  '  - Pré-evoluções continuam disponíveis nas rotas iniciais de cada região.',
  '## [V1.90.1] - 15/05/2026 10:30',
  '### Adicionado',
  '- **Sistema de Batalha de Região (Fase 3)**: ao clicar em "⚔️ Desafiar Região" na Rede de Amigos, o jogador é levado para a tela de desafio da região do amigo (RegionChallengeScreen). Ginásios, Elite Four e Campeão são desafiados em sequência.',
  '- **Simulação de batalha**: batalhas calculadas com base no poder da equipe do jogador vs. o poder total dos inimigos, com fator aleatório de ±20% para variação.',
  '- **Recompensas por batalha**: vitórias rendem PokéCoins e EXP (100-500 moedas por batalha dependendo do tipo de adversário).',
  '- **Tela de conclusão**: ao vencer o Campeão, exibe tela de comemoração com total de recompensas ganhas.',
  '- **Verificação de nome único**: ao criar personagem, o nome do treinador é verificado no Firestore para garantir que não está em uso por outro jogador.',
  '## [V1.90.0] - 15/05/2026 09:00',
  '### Segurança',
  '- **Firestore Security Rules**: adicionado arquivo `firestore.rules` com regras completas. `saves` privados, `users`/`userRegions`/`bossRankings` públicos para leitura (apenas o dono escreve), `friends/requests` criado só pelo remetente, `friends/list` privado por uid.',
  '### Corrigido',
  '- **Gate Elite Four**: compra de slots da Elite Four agora requer todos os 8 ginásios comprados. Compra do Campeão requer Elite Four completa (4 slots). Antes o aviso aparecia mas não bloqueava.',
  '- **Validação ao publicar região**: antes de publicar, Pokémon que o jogador não possui mais são removidos automaticamente dos times. Times que ficam vazios voltam para estado "não configurado".',
  '- **Confirmação de publicação**: modal de confirmação exibido antes de publicar região ("Publicar Região?"), com cancelar e confirmar. Despublicar é direto (sem confirmação).',
  '- **Perfil de amigo atualizado**: ao aceitar solicitação de amizade, busca o perfil fresco do Firestore em vez de usar o snapshot antigo da solicitação.',
  '### Melhorado',
  '- **Busca de amigos case-insensitive**: campo `nameLower` adicionado ao doc público do usuário. Busca por "ash" encontra "Ash", "ASH", etc. Compatível com usuários antigos via fallback.',
  '- **Debounce na busca**: campo de nome aguarda 800ms após o usuário parar de digitar antes de consultar o Firestore (a partir de 3 caracteres). Enter ainda busca imediatamente.',
  '- **Rate limit em solicitações**: intervalo mínimo de 30s entre solicitações para o mesmo destinatário, prevenindo spam.',
  '- **Loading state em "Desafiar Região"**: botão fica desabilitado e exibe "⏳ Carregando..." durante a consulta ao Firestore. Evita cliques múltiplos e requisições duplicadas.',
  '## [V1.89.9] - 15/05/2026 08:30',
  '### Reorganização',
  '- **Rede de Amigos → Menu**: o card "Rede de Amigos" foi movido da Cidade para o Menu principal. Badge vermelho de solicitações pendentes aparece no card do Menu.',
  '- **Cidade — "Minha Região"**: card na Cidade renomeado de "Construtor de Região" para "Minha Região". Sempre visível na Cidade (não requer slot comprado para aparecer).',
  '## [V1.89.8] - 15/05/2026 08:15',
  '### Adicionado',
  '- **Sistema de Região Personalizada**: cada jogador pode montar sua própria sequência de até 8 ginásios, 4 membros da Elite Four e 1 Campeão. Slots são comprados individualmente na Loja de Prestígio (aba "Liga").',
  '- **Loja de Prestígio — Aba Liga**: nova aba "Liga" exibe os slots de ginásio (Nv.14-84), Elite Four (Nv.88-94) e Campeão (Nv.98), com compra sequencial e visualização de slots adquiridos.',
  '- **Minha Região (RegionBuilderScreen)**: tela completa para configurar cada ginásio (tipo, líder, sprite de treinador, equipe de até 6 Pokémon), membros da Elite Four e Campeão. Pokémon disponíveis são os capturados pelo jogador.',
  '- **Publicação de Região**: na aba "Publicar", o jogador pode dar um nome à sua região e ativá-la. Região publicada fica disponível para amigos desafiarem.',
  '- **Desafiar Região de Amigo**: na Rede de Amigos, o botão "⚔️ Desafiar Região" fica ativo quando o amigo tem uma região publicada.',
  '- **Sync Firestore**: região publicada é sincronizada em `userRegions/{uid}` e o campo `hasRegion` é atualizado no documento público do usuário (`users/{uid}`).',
  '## [V1.89.7] - 15/05/2026 07:39',
  '### Adicionado',
  '- **Rede de Amigos**: novo menu "Rede de Amigos" na Cidade com 3 abas: Amigos (lista de amigos aceitos), Solicitações (aceitar/recusar pedidos recebidos) e Buscar (pesquisa por nome exato de treinador).',
  '- **Solicitações em tempo real**: solicitações de amizade pendentes são monitoradas via Firestore `onSnapshot` — o badge vermelho no botão da Cidade atualiza automaticamente sem precisar recarregar.',
  '- **Trainer Card dos amigos**: ao buscar ou ver solicitações, é exibido um card compacto com sprite do treinador, nível, Power Score, badges, Pokédex count, shinies e chips de regiões vencidas.',
  '- **Sync de aparência no cloud**: campos `appearance`, `selectedTitle` e `prestige` agora são sincronizados na coleção pública `users` para permitir renderização correta do card de amigos.',
  '- **Remoção de amigos com confirmação**: botão "Remover" exibe modal de confirmação antes de desfazer amizade de forma bidirecional.',
  '- **Botão "Batalhar" reservado**: o botão de batalha entre amigos está visível na lista mas desabilitado, preparado para o sistema de batalhas multiplayer.',
  '## [V1.89.6] - 15/05/2026 07:29',
  '### Alterado',
  '- **Loja de Prestígio — Sprites de Avatar**: sprites com custo agora exigem compra explícita além do requisito de progresso. Ter a flag de progresso (ex: campeão de Kanto) apenas libera a opção de comprar — o sprite NÃO é mais desbloqueado automaticamente. Sprites gratuitos (custo 0) continuam se desbloqueando automaticamente ao atingir o progresso.',
  '### Adicionado',
  '- **Loja de Prestígio — Modal "Equipar agora?"**: ao comprar um sprite de avatar, um modal desliza na tela com os botões "✓ Equipar" e "Agora não". Equipar substitui imediatamente o avatar no Trainer Card.',
  '- **Loja de Prestígio — Estados visuais de sprites**: cards de sprite agora exibem 5 estados distintos: Equipado (dourado), Disponível para equipar (verde), Disponível para comprar (azul + preço), Sem coins suficientes (preço em vermelho), Bloqueado por progresso (cadeado roxo).',
  '## [V1.89.5] - 15/05/2026 07:20',
  '### Balanceamento',
  '- **Raids — Frequência reduzida**: gatilho de surgimento de raids dobrado de 100 para 200 batalhas. Raids agora aparecem com metade da frequência anterior.',
  '### Adicionado',
  '- **Trainer Card — Títulos de Campeão Regional**: adicionados 10 novos títulos desbloqueáveis: "Campeão de Kanto", "Campeão de Johto", "Campeão de Hoenn", "Campeão de Sinnoh", "Campeão de Unova", "Campeão de Kalos", "Campeão de Alola", "Campeão de Galar", "Campeão de Paldea" e o raro "Campeão das 9 Regiões — Lenda Mundial".',
  '## [V1.89.4] - 15/05/2026 07:17',
  '### Melhorado',
  '- **Rotas — Habitat Regional oculto**: as áreas "Habitat Regional I, II e III" não aparecem mais na lista de rotas até o jogador se tornar Campeão da liga daquela região. Isso deixa a tela de rotas mais limpa para jogadores que ainda não completaram a liga.',
  '## [V1.89.3] - 15/05/2026 07:09',
  '### Corrigido',
  '- **Deduplicação de espécies — Captura**: `ownsSpecies` agora verifica também os Pokémon cuidadores da casa (`house.caretakers`). Capturas de espécies já presentes como cuidadores não mais geram duplicatas.',
  '- **Deduplicação de espécies — Raids**: detecção de espécie já capturada em raids agora inclui cuidadores da casa.',
  '- **Deduplicação de espécies — Safari Zone**: capturas na Safari Zone agora verificam duplicatas no time, PC e cuidadores antes de adicionar. Se já possui a espécie, converte em EXP Candy S.',
  '- **Deduplicação de espécies — Evolução**: ao completar uma evolução, quaisquer cópias da forma evoluída no PC, cuidadores da casa ou outros slots do time são automaticamente removidas e convertidas em EXP Candy S.',
  '## [V1.89.2] - 15/05/2026 07:00',
  '### Balanceamento',
  '- **Raid — HP reduzido**: multiplicadores de HP revisados para tornar todas as estrelas derrotáveis no tempo limite de 60s. 4★: 50→18 (-64%), 5★: 150→40 (-73%). Anteriormente raids de 4★ eram impossíveis de derrotar.',
  '## [V1.89.1] - 15/05/2026 06:54',
  '### Melhorado',
  '- **Equipe — Botão Contextual**: botão "Voltar ao Treino" renomeado para "🗺️ Voltar para Rota". Durante lutas de Ginásio/Rival/Elite, o botão vira "⚔️ Voltar para Batalha" com destaque em vermelho.',
  '- **Equipe — Acesso durante batalha VS**: abrir a tela de Equipe durante uma luta de Ginásio agora mantém a batalha em segundo plano, permitindo retorno sem perder o progresso.',
  '- **Confirmação ao sair durante luta**: tentar ir à Cidade ou Rotas enquanto há uma batalha chave em andamento exibe um aviso de confirmação antes de cancelar a luta.',
  '## [V1.89.0] - 15/05/2026 06:30',
  '### Corrigido',
  '- **Raid — Animação de Pokébola**: a bola agora voa e pousa exatamente sobre o sprite do Pokémon (posição calculada dinamicamente com `getBoundingClientRect`). Mensagens "✨ Capturado!" e "💨 Escapou!" aparecem logo abaixo do sprite.',
  '- **Raid — Shakings sem translateY**: as animações de tremida, brilho e fuga foram reescritas sem dependência de offsets fixos — funcionam corretamente em qualquer tamanho de tela.',
  '## [V1.88.9] - 15/05/2026 06:00',
  '### Corrigido',
  '- **Raid — Botão "Continuar e tentar derrotar"**: ao pressionar o botão, a luta agora continua normalmente sem voltar para a fase de captura. O combate prossegue até o HP do Boss chegar a 0 (recompensas) ou o tempo acabar (encerrado). A flag `continuingFromCapture` garante que o limiar de 30% de HP não re-ative a fase de captura.',
  '## [V1.88.8] - 14/05/2026 22:10',
  '### Adicionado',
  '- **Tutorial de Boas-Vindas**: Modal de 6 passos exibido automaticamente na primeira visita à Cidade após capturar o starter.',
  '- **Passo Cidade**: Explica Poke Center, Poke Mart, Forja, Explorações e Casa.',
  '- **Passos Completos**: Rotas → Cidade → Rivais & Equipe Vilã → Ginásios & Liga → Raids → Boss Mundial.',
  '- **Progresso Visual**: Barra de progresso no topo com marcadores por passo. Botões Anterior/Próximo e "Começar Aventura!" no último.',
  '## [V1.88.5] - 14/05/2026 19:23',
  '### Alterado',
  '- **Habitats Regionais**: áreas Habitat I, II e III agora exigem ser Campeão da região antes de serem liberadas — válido para todas as 9 regiões (Kanto, Johto, Hoenn, Sinnoh, Unova, Kalos, Alola, Galar, Paldea).',
  '## [V1.88.4] - 14/05/2026 19:19',
  '### Adicionado',
  '- **Botão Sair**: botão "Sair da Conta" na tela inicial para deslogar e retornar à tela de login.',
  '### Corrigido',
  '- **Ícone Minha Casa**: substituído por casinha em SVG com temática cartoon/Pokémon (telhado vermelho, janelas, porta e chaminé).',
  '## [V1.88.3] - 14/05/2026 19:07',
  '### Corrigido',
  '- **Forja (Bug Crítico)**: itens não eram fabricados mesmo após confirmação. Validação agora soma materials + items (igual à UI), deduzi materials primeiro e items depois.',
  '## [V1.88.2] - 14/05/2026 18:55',
  '### Corrigido',
  '- **Trainer Card**: mais espaço para o título abaixo do nome, label de região sem corte, ícone de campeão trocado por troféu SVG dourado.',
  '## [V1.88.1] - 14/05/2026 18:52',
  '### Corrigido',
  '- **Barra Superior**: botão de som agora exibe ícone SVG de alto-falante; botão Home exibe ícone SVG de casa.',
  '## [V1.88.0] - 14/05/2026 18:48',
  '### Adicionado',
  '- **Raid — Opções na Fase de Captura**: botões "Continuar e tentar derrotar" (volta à fase de luta) e "Sair sem capturar" (encerra a raid sem captura) agora disponíveis na tela de Raid.',
  '- **Clima por Golpe**: Sunny Day, Rain Dance, Sandstorm e Hail ativam o clima correspondente por 5 turnos; ao fim, o clima volta ao natural da rota.',
  '### Corrigido',
  '- **Banner de Raid (Mobile)**: notificação de Raid restruturada em bloco — título não é mais cortado, botão OK virou faixa larga (44px) para facilitar toque no celular.',
  '### Alterado',
  '- **Sistema de Clima**: rotas comuns não geram mais clima aleatório; apenas biomas especiais mantêm clima fixo (Deserto → Sandstorm, Neve/Gelo → Hail).',
  '## [V1.87.0] - 14/05/2026 18:27',
  '### Adicionado',
  '- **Safari Zone Interativa**: Nova tela dedicada com captura sem batalha, 30 Safari Balls por sessão, Pokémon exclusivos (Exeggcute, Lickitung, Chansey, Tangela, Kangaskhan, Scyther, Pinsir, Tauros).',
  '- **Mecânicas da Safari Zone**: Sistema de Isca (-40% fuga, +30% captura) e Lama (+50% captura, +50% fuga). Diferentes estratégias de captura!',
  '- **Mega Evolução Permanente**: Sistema completo de Mega Evolução definitiva. Uma vez realizada, o Pokémon não retorna à forma normal.',
  '- **25+ Mega Evoluções**: Charizard X/Y, Blastoise, Venusaur, Alakazam, Gengar, Gyarados, Kangaskhan, Pinsir, Aerodactyl, Ampharos, Scizor, Heracross, Houndoom, Tyranitar, Blaziken, Gardevoir, Mawile, Aggron, Medicham, Manectric, Banette, Absol, Salamence, Metagross, Lucario, Abomasnow.',
  '- **Bônus de Stats Permanentes**: Cada Mega Evolução aumenta permanentemente ataque, defesa, velocidade e tipos do Pokémon.',
  '- **Tela Mega Evolução**: Interface dedicada com comparação visual antes/depois, bônus detalhados e animação épica.',
  '- **Indicador Mega no Time**: Pokémon Mega evoluídos exibem o sprite da forma Mega e a tag visual no gerenciamento.',
  '## [V1.86.0] - 14/05/2026 16:30',
  '### Adicionado',
  '- **Sistema de Clima**: Sol, Chuva, Tempestade de Areia e Granizo gerados automaticamente ao entrar em rotas.',
  '- **Multiplicadores de Clima**: Fogo +50% no Sol, Água +50% na Chuva, Rock/Ground/Steel +20% na Tempestade de Areia, Gelo +20% no Granizo.',
  '- **Dano Passivo de Clima**: Sandstorm e Hail causam 1/16 HP por turno (imunes: tipos Rock/Ground/Steel e Ice respectivamente).',
  '- **Indicador Visual**: Ícone e nome do clima exibidos no campo de batalha.',
  '- **Biomas com Clima Fixo**: Deserto → Tempestade de Areia, Neve → Granizo, Praia → Chuva.',
  '- **Receitas Safari Zone**: Safari Ball, Isca Pokémon e Bola de Lama agora craftáveis na Forja.',
  '## [V1.85.3] - 14/05/2026 15:32',
  '### Corrigido',
  '- **Fix de Ícone de Recompensa**: Ícone de moeda nas recompensas de Raid corrigido (relic-gold-coin → nugget).',
  '## [V1.85.2] - 14/05/2026 15:20',
  '### Balanceamento',
  '- **Raids**: Padronizado para 5 tentativas de captura em todas as estrelas.',
  '- **Dificuldade de Captura**: A dificuldade agora escala pela probabilidade por arremesso (1★=1.5x até 5★=0.15x).',
  '## [V1.85.1] - 14/05/2026 11:08',
  '### Corrigido',
  '- **Fix de Seleção de Títulos**: Modais agora utilizam `createPortal` para evitar conflitos de z-index no TrainerCard.',
  '- **Fix de Taxa de Captura de Raids**: `RAID_CATCH_RATE_MULT` corrigido para objeto, permitindo que a dificuldade escale por estrelas (1★-5★).',
  '- **Power Score Modal**: Atualizado para o padrão de Portal, resolvendo problemas de clique.',
  '## [V1.85.0] - 14/05/2026 10:45',
  '### Adicionado',
  '- **Confirmar Forja**: Adicionado modal de confirmação ao fabricar itens para evitar gastos acidentais.',
  '### Corrigido',
  '- **Fix de Imagens do Trainer Card**: Atualizados os ícones de campeão regional (Johto, Hoenn, Alola, Paldea) para sprites oficiais da PokeAPI.',
  '- **UX de Seleção de Título**: Adicionado delay suave ao fechar o seletor de títulos para melhor feedback visual.',
  '- **Lógica da Forja**: Refatorada a função `handleCraft` para processar custos de forma atômica e robusta.',
  '## [V1.84.4] - 14/05/2026 10:27',
  '### Corrigido',
  '- **Prop Destructuring Fix**: Corrigido ReferenceError no TrainerCard ao acessar funções de estado de modal não desestruturadas.',
  '## [V1.84.3] - 14/05/2026 10:10',
  '### Corrigido',
  '- **Critical State Fix**: Corrigido erro de Temporal Dead Zone (ReferenceError) no AppRoot ao inicializar modais.',
  '## [V1.84.2] - 14/05/2026 09:55',
  '### Corrigido',
  '- **Critical Init Fix**: Resolvido erro de inicialização (ReferenceError) movendo constantes para o topo e desacoplando REGION_ORDER para evitar ciclos de importação.',
  '## [V1.84.1] - 14/05/2026 09:37',
  '### Corrigido',
  '- **Initialization Fix**: Restaurado o export `EXP_CANDIES` e corrigida a importação de `REGION_ORDER` para evitar erros de inicialização (ReferenceError).',
  '## [V1.84.0] - 14/05/2026 09:12',
  '### Adicionado',
  '- **Pool Cross-Region**: Raids agora podem sortear Pokémon de regiões anteriores (35% de chance).',
  '- **Sprites Shiny**: Pokémon shiny em raids agora exibem corretamente sua sprite brilhante.',
  '### Corrigido',
  '- **Ícones de Recompensa**: Todos os ícones de recompensa de raids foram corrigidos e agora utilizam o PokeAPI com fallbacks seguros.',
  '- **Sincronização de Itens**: Corrigido ID de Pokébola nas recompensas de raid para compatibilidade com o inventário.',
  '## [V1.83.6] - 14/05/2026 09:04',
  '### Corrigido',
  '- **Estabilização de Interatividade UI**: Finalizada a arquitetura de modais para eliminar vazamentos de eventos.',
  '- **Sincronização de Estado**: Estados de modais (Títulos, Power Rank, Forja e Confirmação) consolidados no AppRoot.',
  '- **Bloqueio de Fundo**: Implementado bloqueio físico via `pointer-events: none` na CityScreen e CraftingStation sempre que um modal estiver ativo.',
  '- **Landing Screen Fix**: Restaurada a integridade visual da tela inicial e corrigida a duplicação do Ranking Global.',
  '## [V1.83.5] - 14/05/2026 08:48',
  '### Corrigido',
  '- **Standard Confirmation Flow**: Revertida paleta para Dark/Pokémon (Slate/Blue) e removido stopPropagation de botões internos.',
  '- **Independent Interaction**: O isolamento da CityScreen agora depende exclusivamente do `pointer-events: none` no container de fundo.',
  '## [V1.83.4] - 14/05/2026 08:44',
  '### Corrigido',
  '- **Simplified Event Isolation**: Removido bloqueio agressivo de propagação e "Escudo Atômico" para restaurar a interatividade natural dos botões.',
  '- **Pointer-Events Strategy**: Migrada toda a lógica de bloqueio de fundo para `pointer-events` via inline style na `CityScreen`.',
  '## [V1.83.3] - 14/05/2026 08:39',
  '### Adicionado',
  '- **Title Selection Preview**: Adicionado modal de confirmação com prévia visual antes de aplicar um novo título.',
  '- **UX Refinement**: Implementado fluxo de dois passos para evitar trocas acidentais, com design system Navy & Green.',
  '## [V1.83.2] - 14/05/2026 08:32',
  '### Corrigido',
  '- **Reactive Title Selection**: Implementada função `handleSelectTitleInApp` com logs de auditoria e persistência explícita no campo `selectedTitle`.',
  '- **Force Re-render**: Adicionada `key` dinâmica ao display de títulos e feedback visual (borda esmeralda) no seletor para confirmação imediata.',
  '## [V1.83.1] - 14/05/2026 08:26',
  '### Corrigido',
  '- **Modal Interactivity**: Restaurada a interatividade dos modais removendo `stopImmediatePropagation` que bloqueava o React.',
  '- **Selection Sync**: Adicionado delay de 50ms na seleção de títulos e logs de diagnóstico para garantir persistência do estado.',
  '## [V1.83.0] - 14/05/2026 08:18',
  '### Corrigido',
  '- **Definitive Pointer Block**: Implementação de estado global `isAnyModalOpen` para desativar fisicamente a `CityScreen` via CSS (`pointer-events: none`).',
  '- **Low-Level Isolation**: Utilização de `stopImmediatePropagation` e logs de depuração para garantir isolamento total nos modais do Trainer Card.',
  '## [V1.82.10] - 14/05/2026 08:02',
  '### Corrigido',
  '- **Técnica do Escudo Duplo**: Bloqueio de propagação no wrapper da lista e delay de 100ms no fechamento do modal para isolamento total contra a CityScreen.',
  '## [V1.82.9] - 14/05/2026 07:46',
  '### Corrigido',
  '- **Atomic Event Shielding**: Introduzido overlay de bloqueio absoluto (z-100004) atrás do Title Picker.',
  '- **Reinforced Selectors**: Botões de seleção de título agora possuem isolamento de eventos em pointerdown/mousedown/click.',
  '## [V1.82.8] - 14/05/2026 07:35',
  '### Corrigido',
  '- **Event Isolation**: Bloqueio total de propagação de cliques no Title Picker e PS Info para evitar interação com a CityScreen ao fundo.',
  '- **Z-Index**: Prioridade absoluta (z-100005) para modais do Trainer Card.',
  '## [V1.82.7] - 14/05/2026 07:20',
  '### Corrigido',
  '- **Sincronização de Versão**: Corrigido bug de cache que impedia a exibição da versão correta no Menu.',
  '- **Cache-Buster**: Implementada verificação de versão com bypass de cache agressivo (`?v=timestamp`).',
  '## [V1.82.6] - 14/05/2026 07:13',
  '### Refatoração',
  '- **Auditoria de Limpeza**: Remoção de ativos obsoletos e código morto.',
  '- **Padronização**: Refatoração de links de recompensas no RaidScreen.',
  '## [V1.82.5] - 14/05/2026 06:56',
  '### Adicionado',
  '- **Animação de Captura (Raids)**: Lançamento de pokébola e efeitos visuais.',
  '## [V1.82.3] - 13/05/2026 22:49',
  '### Adicionado',
  '- **Guia da Jornada**: nova area no MENU com objetivo principal, rota recomendada, proxima rota bloqueada e atalhos para MODO VS ou treino.',
  '- **Diario de Drops**: receitas e materiais uteis agora aparecem no Guia com botao para ir diretamente para a rota de drop quando ela estiver liberada.',
  '## [V1.82.2] - 13/05/2026 22:32',
  '### Corrigido',
  '- **Modais de Vitoria**: recompensas de lideres, rivais, equipe vila e Elite agora exibem exatamente as moedas recebidas apos o rebalanceamento economico.',
  '- **MODO VS/Ginasios**: cards de recompensa passam a mostrar o valor real aplicado no save.',
  '- **Titulos do Trainer Card**: selecao de titulos sincronizada com a Loja de Prestigio e cliques do modal nao vazam mais para outras telas ou para o card expansivel.',
  '## [V1.82.1] - 13/05/2026 22:18',
  '### Adicionado',
  '- **Retencao Diaria**: Nova area de Missoes no MENU com recompensa de login diario, streak, melhor sequencia e ciclos de 7 dias.',
  '- **Missoes Recorrentes**: Inclusas missoes diarias e semanais para derrotas, capturas, treinadores, shinies e raids, usando os contadores persistentes do jogador.',
  '### Corrigido',
  '- **Forja (Mega Pedras)**: Receitas de Mega Stone e fragmentos de Mega Pedra agora so dropam em Kalos apos desbloquear Mega Evolucao.',
  '## [V1.82.0] - 13/05/2026 22:03',
  '### Adicionado',
  '- **Treinador (Interface)**: Redesign completo do TrainerCard com visual premium, glassmorphism e PS (Power Score) detalhado.',
  '- **Sistema de Títulos (Overhaul)**: Novo modal unificado para seleção de títulos (Conquistas + Loja de Prestígio).',
  '- **Títulos (Novos)**: 15+ novos títulos desbloqueáveis (Campeão de Hoenn/Sinnoh, Mestre de Forja, Caçador de Lendas, etc).',
  '### Alterado',
  '- **Economia (Rebalanceamento)**: Redução do multiplicador de moedas em batalhas de treinadores de 0.08 para 0.03 para mitigar a inflação.',
  '### Corrigido',
  '- **Loja de Prestígio**: Corrigido bug de cobrança dupla e garantida a persistência de títulos adquiridos no estado global.',
  '- **Visual (TrainerCard)**: Corrigidos erros de renderização e ícones de insígnias regionais.',
  '## [V1.81.2] - 13/05/2026 21:42',
  '### Alterado',
  '- **Raids (Balanceamento)**: Redução drástica do HP dos Pokémon de Raid (multiplicadores reduzidos em ~60%).',
  '- **Raids (Dano)**: Aumento da contribuição de dano do jogador em rotas para a Raid de 50% para 80%.',
  '## [V1.81.1] - 13/05/2026 21:23',
  '### Corrigido',
  '- **Raids (HP)**: Corrigido bug que causava HP inválido (NaN) em Pokémon de Raid ao converter o multiplicador de HP para um sistema de escala por estrelas.',
  '## [V1.81.0] - 13/05/2026 21:10',
  '### Concluído',
  '- **Sincronização de Milestone**: Consolidação de melhorias visuais, correções de evolução e rebalanceamento econômico.',
  '- **Deploy Final**: Sincronização completa de ativos e lógica de recompensa.',
  '## [V1.80.9] - 13/05/2026 21:09',
  '### Alterado',
  '- **Economia**: Redução do multiplicador de recompensa de treinadores de 0.20 para 0.08 (redução de ~60%) para equilibrar a progressão.',
  '## [V1.80.8] - 13/05/2026 21:04',
  '### Adicionado',
  '- **Imagens Premium**: Adicionadas novas artes em pixel-art de alta fidelidade para itens chave: Fire Stone, Water Stone, Link Cable e Rare Candy.',
  '### Corrigido',
  '- **Mochila (Visual)**: Corrigido bug de caminhos de imagem que impedia a exibição de ícones locais no GitHub Pages (implementação de `assetPath`).',
  '- **Menu**: Corrigida a exibição de EXP Candies que estava com a propriedade de imagem incorreta.',
  '## [V1.80.7] - 13/05/2026 23:57',
  '### Corrigido',
  '- **Evoluções por Troca**: 8 Pokémon (Boldore, Gurdurr, Phantump, etc.) agora evoluem via `link_cable` em vez de nível.',
  '- **Clobbopus**: Nível de evolução corrigido de 20 para 35.',
  '## [V1.80.6] - 13/05/2026 23:56',
  '### Corrigido',
  '- **Evoluções (Correção)**: Atualizadas 18 linhas evolutivas (Lampent, Tadbulb, Floette, etc.) para usarem pedras evolutivas em vez de nível, respeitando a mecânica oficial.',
  '## [V1.80.5] - 13/05/2026 23:55',
  '### Adicionado',
  '- **Sistema de Candies (Expansão Global)**: Candies agora disponíveis para TODAS as 9 gerações (1025 Pokémon).',
  '- **Famílias Evolutivas**: Implementada lógica de agrupamento automático por família (ex: Chikorita Candy serve para Chikorita, Bayleef e Meganium).',
  '- **Visual**: Ícones de Candy agora usam sprites do Pokémon base da família via PokeAPI, garantindo suporte a todos os novos Pokémon.',
  '## [V1.80.4] - 13/05/2026 20:30',
  '### Melhorado',
  '- **Forja (Crafting)**: Introduzido seletor de quantidade (x1, x10, Max) e exibição da quantidade de itens já possuídos.',
  '- **TMs (Interface)**: Adicionado sistema de filtragem por tipo elemental para facilitar a escolha de golpes.',
  '- **Forja (Correção)**: Custos em Pokédollars agora são corretamente deduzidos ao fabricar itens.',
  '## [V1.80.3] - 13/05/2026 20:25',
  '### Melhorado',
  '- **Raids (Variedade)**: Pool de Pokémon expandida em todas as regiões (adicionados Nidoking, Rhydon, Scizor, Alakazam, etc).',
  '- **Raids (Aleatoriedade)**: Introduzida variância de nível (+/- 1) para que cada encontro seja único dentro da sua categoria.',
  '## [V1.80.2] - 13/05/2026 19:56',
  '### Corrigido',
  '- **Raids (Visual)**: Sprites de recompensa (TMs, EXP Candies, Shards) agora usam artes customizadas em pixel-art de alta fidelidade e são servidos localmente, eliminando imagens quebradas.',
  '- **Mochila/Inventário**: Ícones de materiais raros (Armor Fragment, Mega Stone Shard) atualizados para artes premium em vez de emojis.',
  '## [V1.80.1] - 13/05/2026 19:23',
  '### Corrigido',
  '- **Raids (Bug Crítico)**: raids agora usam corretamente a região ativa do jogador (`activeRegion`) — antes usavam sempre Kanto por referir `currentRegion` (campo inexistente).',
  '- **Raids**: estrelas máximas calculadas pelo número de insígnias da região atual do jogador.',
  '- **Forja (Categorias)**: ícones de categoria substituídos por sprites de item PokeAPI (sem emojis).',
  '## [V1.80.0] - 13/05/2026 23:00',
  '### Corrigido',
  '- **MENU**: ícones corrigidos (pokedex, mochila, salvar agora aparecem corretamente).',
  '- **Estatísticas**: cards com ícone centralizado e layout mais limpo.',
  '- **Forja (Cidade)**: CIDADE > FORJA POKEMON agora usa o mesmo componente moderno da Forja, com receitas bloqueadas/desbloqueadas corretamente.',
  '### Melhorado',
  '- **Forja**: separação por categoria reformulada — bolsos visuais com emoji, caption e contador de desbloqueadas/total.',
  '## [V1.79.9] - 13/05/2026 21:30',
  '### Adicionado',
  '- **Sprites de Treinadores (Equipes)**: villains.js corrigido — Aqua/Magma/Galáctica agora usam sprites corrigidos; 6 novas equipes adicionadas (Plasma, Flare, Skull, Rainbow Rocket, Yell, Star).',
  '- **Avatares da Loja de Prestígio**: ~40 novos avatares adicionados cobrindo todos os rivais, líderes e personagens icônicos de todas as 9 regiões.',
  '- **Treinadores Gen9 em Paldea**: tipos exclusivos de Paldea (Estudante, Delinquente, Operário, Entregador, Cozinheiro) agora aparecem nas rotas regionais.',
  '### Corrigido',
  '- **Florian/Juliana**: sprites dos protagonistas de Paldea corrigidos para `florian-s.png` e `juliana-s.png`.',
  '## [V1.79.8] - 13/05/2026 20:00',
  '### Adicionado',
  '- **Modal Mega Evolução**: Prof. Sycamore aparece após vencer o 1º Ginásio de Kalos (Viola) explicando o sistema de Mega Evolução.',
  '- **Bloqueio de Mega Pedras**: categoria Mega Stones na Forja fica oculta até desbloquear Mega Evolução em Kalos.',
  '### Corrigido',
  '- **Shiny Rate**: taxa ajustada para exatamente 1/4000 (base), 1/2000 (maestria 100+) e 1/1000 (maestria 200+).',
  '## [V1.79.7] - 13/05/2026 17:38',
  '### Adicionado',
  '- **Menu Estatisticas**: nova area no MENU com tempo de jogo, Pokedex, capturas, derrotas, shinies, treinadores, equipe vila, boss de area, raids e dano em boss.',
  '- **Player Stats Persistente**: progresso passa a registrar contadores de captura, batalha, shiny, boss, raid e tempo ativo de jogo.',
  '### Melhorado',
  '- **Mochila Mobile**: categorias viraram bolsos grandes em grade, com sprites de itens, contadores claros e cards de item maiores para toque em celular.',
  '## [V1.79.1] - 13/05/2026 15:47',
  '### Corrigido',
  '- **Sistema de Raids**: Corrigido erro de ícones quebrados no modal de recompensas.',
  '- **Balanceamento de Raids**: Redução das quantidades de EXP Candy e Rare Candy nas recompensas.',
  '- **Lógica de Vitória**: Recompensas de Raid agora exigem a derrota ou captura do Boss.',
  '## [V1.79.0] - 13/05/2026 15:12',
  '### Adicionado',
  '- **Mega Evoluções (Sistema Global)**:',
  '    - Lançamento oficial com 96 novas formas e branching paths.',
  '    - Sincronização total de itens evolutivos e Pokedex.',
  '    - Novas receitas na Forja e economia de Mega Shards.',
  '## [V1.78.4] - 13/05/2026 12:35',
  '### Adicionado',
  '- **Expansão Total de Mega Stones**:',
  '    - Implementadas receitas para TODAS as Mega Stones conhecidas (46 pedras ao todo).',
  '    - Todas as receitas agora dropam de Pokémon capazes de Mega Evoluir na região de Kalos.',
  '    - Atualizado o guia de drop na Forja para mostrar todos os Pokémon que fornecem fragmentos.',
  '## [V1.78.3] - 13/05/2026 12:25',
  '### Adicionado',
  '- **Sistema de Mega Evolução (Alpha)**:',
  '    - Mega Evoluções agora são possíveis em Kalos!',
  '    - Adicionado item "Fragmento de Mega Pedra" como drop raro (15%) de Pokémon capazes de Mega Evoluir em Kalos.',
  '    - Nova categoria na Forja: Mega Stones.',
  '    - Adicionadas receitas para Charizardite X/Y, Venusaurite, Blastoisinite, Lucarionite e Garchompite.',
  '    - Mega Evoluções registradas na Pokedex: Mega Venusaur, Charizard X/Y, Blastoise, Lucario e Garchomp.',
  '- **Refinamento de Raids**:',
  '    - Estrelas das Raids agora são estritamente limitadas pelo progresso regional (insígnias).',
  '    - Pool de Raids em Kalos expandida e priorizada com Pokémon da região (Talonflame, Aegislash, Goodra, etc).',
  '    - UI de Dano Contribuído na Raid modernizada para melhor visualização.',
  '## [V1.78.2] - 13/05/2026 12:12',
  '### Adicionado',
  '- **Sistema de Raids**:',
  '    - Adicionada chance de 0.5% de spawn imediato ao encontrar Pokémon selvagens nas rotas.',
  '    - Corrigido bug onde Raids expiradas bloqueavam o surgimento de novas.',
  '    - Reduzido tempo de spawn passivo para 1 hora.',
  '## [V1.78.0] - 13/05/2026 11:36',
  'UI: Redesign completo da tela de Raid com sprite centralizado e melhor legibilidade',
  'UI: Botões de ação da Raid agora possuem alto contraste (Branco/Preto) para melhor navegação',
  'System: Raids agora podem surgir aleatoriamente durante encontros nas rotas (0.5% de chance)',
  'Fix: Corrigida trava que impedia novas Raids se a anterior expirasse sem ser visualizada',
  'System: Intervalo de spawn automático de Raids reduzido de 6h para 1h',
  'System: Taxa de Pokémon Shiny padronizada para 1/4096 (escala progressiva por maestria)',
  'System: Gatilho de Raids ajustado para 50 batalhas (selvagens ou treinadores)',
  'Fix: Textos flutuantes (+HP, Buffs/Debuffs) agora aparecem sobre o Pokémon correto na batalha',
  'Fix: Duplicação de Pokémon em expedições resolvida (Pokémon agora permanecem no PC com status onExpedition)',
  'UI: Badge de status e travas de segurança adicionadas ao gerenciamento de Pokémon para expedições',
  'Fix: Notificações redundantes de receitas de forja resolvidas (correção de dependências de estado)',
  'Fix: Navegação do botão "CIDADE" corrigida para levar à Cidade em vez do Mapa',
  'Fix: Padronização total da taxa de spawn de todos os 27 Pokémon iniciais (Starters) para spawnWeight 10 (~1% chance)',
  'Fix: Implementação de trava de progresso para todos os starters: spawns agora exigem derrota do primeiro rival de sua região',
  'Fix: Iniciais de todas as 9 gerações — spawnWeight padronizado em 10 para ~1% de chance',
  'Fix: Encontros com iniciais em todas as regiões agora exigem a derrota do primeiro rival',
  'Fix: Iniciais de Johto/Hoenn/Sinnoh — spawnWeight aumentado de 2→10 para taxa de aparição equivalente a Kanto (~1%)',
  'Fix: Ícones de região (Johto/Hoenn/Alola/Paldea) trocados para sprites dos lendários via PokeAPI',
  'Fix: Ícone do título Rival trocado para scope-lens (blue-card era 404)',
  'Fix: Imagens do Pokémart/Forja — link_cable, poke_food, poke_food_premium agora usam PokeAPI',
  'UX: Seleção de título — delay de 200ms antes de fechar modal para mostrar badge Ativo',
  'Fix: Materiais de Forja agora dropam em todas as 9 regiões via TYPE_MATERIAL_MAP',
  'Feature: FORGE_MATERIAL_DROP_GUIDE expandido com 200+ novos Pokémon de todas as gerações',
  'Feature: Efeitos visuais de golpes — 120+ moves with animações únicas usando sprites do Pokémon Showdown (/fx/)',
  'Feature: Motor MoveAnimationLayer — 12 tipos de animação (projectile, burst, drain, quake, beam, slash, etc.)',
  'Feature: Fallback por tipo — todo golpe sem animação específica recebe visual baseado no seu tipo',
  'Feature: Efeitos secundários completos — Drain cura HP, Recoil dá dano próprio, Power-Up Punch/Flame Charge buffam stats, 6 tipos de chance de status em golpes de dano',
  'Release: V1.77.0 — Sistema completo de Held Items: 18 tipos + 4 especiais com efeitos de batalha',
  'Feature: TYPE_BOOSTS expandido para todos os 18 tipos (Silk Scarf, Miracle Seed, Never-Melt Ice, etc.)',
  'Feature: Life Orb — +30% dano + -8% HP de recuo por turno ao atacar',
  'Feature: Expert Belt — +20% dano adicional em golpes super efetivos',
  'Feature: Leftovers — recupera 5% HP por turno automaticamente',
  'Feature: Focus Sash — sobrevive a um golpe fatal com 1 HP (se HP era > 1)',
  'Feature: RECIPE_LABEL_OVERRIDES — dicas de localização para receitas de todos os held items',
  'Release: V1.76.9 consolidando Loja de Prestigio, Expedições e Minha Casa com cache publico atualizado',
  'Fix: Minha Casa — plantio agora respeita todos os slots disponiveis e consome sementes por canteiro',
  'Fix: Expedições — relatório de conclusão estabilizado, sem piscar e com botão de fechar funcionando',
  'UI: Expedições — recompensas agora exibem sprites de itens e Pokémon com fallbacks estáveis',
  'UX: Expedições — iniciar uma expedição mantém o jogador na área de expedições e respeita a duração escolhida',
  'UI: Loja de Prestigio refinada com abas tematicas, sprites Pokemon e fallbacks para icones quebrados',
  'UI: Estandartes de ginasio receberam icones de tipo e visual mais colecionavel',
  'Fix: Header, badges e moedas da Loja de Prestigio trocados para assets estaveis',
  'UX: Melhoria de Fluxo — adicionada confirmação de destino após batalhas de história (Rival/Equipes)',
  'UI: Ajustes Visuais — corrigido posicionamento da Loja de Prestígio, ícone da aba Ginásio e layout das insígnias',
  'Fix: Navegação da Forja — corrigido erro de redirecionamento que causava tela branca ao sair do modal de receita',
  'Feature: Raids Aprimoradas — gatilho de batalhas reduzido para 100 e nova arte de fundo épica para a tela de raid',
  'Feature: Sistema de Itens Segurados — agora é possível equipar itens forjados (Charcoal, Magnet, etc.) nos Pokémon para ganhar bônus de dano e efeitos especiais',
  'Fix: Imagens de Expedição — corrigido o caminho das imagens de fundo para compatibilidade com GitHub Pages',
  'UI: Loja de Prestígio — nova interface premium com ícones de pixel art e navegação otimizada para mobile',
  'Fix: Drop de Receitas — corrigido bug que permitia dropar receitas já conhecidas e disparar modal indevidamente',
  'Feature: Confirmação de EXP Candy — modal com prévia de XP antes/depois, badge de Level Up e botão Voltar',
  'Feature: Modal de Receita Encontrada — celebração visual com nome, ícone e efeito do item ao dropar receita',
  'Fix: Raid sem Pokébolas — botão "Fechar" e "Recompensas" visíveis quando todas as bolas chegam a zero',
  'Fix: Ícones do Menu corrigidos — Pokédex 📕, Mochila 🎒 e Salvar 💾 agora usam emoji (100% confiável)',
  'Fix: Avatar Leaf — sprite corrigido (leaf.png→green.webp no PS, era 404)',
  'Fix: Avatar Florian/Juliana — sprites de Paldea corrigidos (florian→giacomo, juliana→penny)',
  'Fix: onError em todos os sprites de treinador — fallback para Red em vez de sumir',
  'UI: Modal de Expedição restaurado — ícones de itens (ITEM_LABELS), sprites dos Pokémon e visual completo',
  'Fix: Modal Galar→Paldea exibia Prof. Magnolia em vez de Prof. Sada (duplicate professor corrigido)',
  'Audit: Sistema de progressão entre regiões verificado — todas as 9 transições estão corretas',
  'Fix: Totodile em Johto — rota 30 corrigida (unlockLevel 61, req johto_route_29_cleared, requiresFlag no Totodile)',
  'Fix: Auditoria completa de iniciais — todos os 26 Pokémon iniciais confirmados em todas as 9 regiões',
  'Fix: Pikachu em Viridian Forest — adicionado forceSpawn para bypass do filtro de evoluídos em rotas lvl≤15',
  'Fix: Iniciais pós-rival — Kanto/Johto/Hoenn/Sinnoh agora exigem derrota do rival (requiresFlag)',
  'Fix: Iniciais geração 5-9 — formas base corretas (Snivy/Tepig/Oshawott etc.) em vez de evoluções finais',
  'Balance: Distribuição corrigida — máx 2 iniciais por rota, 3º inicial na rota intermediária (forma base)',
  'Fix: buildRegionRoutes — starters removidos da route_1; starterBases usados nas rotas iniciais extras',
  'Balance: Economia drasticamente rebalanceada — coins por Pokémon selvagem 10x mais difícil (level×0.15)',
  'Balance: Recompensa de treinadores reduzida em 80% (multiplicador 0.20 aplicado globalmente)',
  'Balance: Encounters iniciais corrigidos — máx 2 iniciais por rota, distribuídos em todas as gerações',
  'Kanto: Rota 1 → Bulbasaur+Charmander | Rota 22 → Squirtle+Eevee | Viridian Forest → Pikachu (pós rival)',
  'Johto: Rota 29 → Chikorita+Cyndaquil | Rota 30 → Totodile (pós rival)',
  'Hoenn: Rota 101 → Treecko+Torchic | Rota 102 → Mudkip',
  'Sinnoh: Rota 201 → Turtwig+Chimchar | Rota 202 → Piplup',
  'Unova/Kalos/Alola/Galar/Paldea: inicial[0]+[1] na rota 1, inicial[2] na rota inicial secundária',
  'Fix: Loja de Prestígio — tela azul ao acessar aba Avatar corrigida (hook fora de IIFE)',
  'UI: Avatar — card de preview ao vivo com glow dinâmico da moldura e gradiente do fundo',
  'UI: Avatar Sprites — agrupados por região com cabeçalhos, grid 3 colunas, overlay de bloqueio',
  'UI: Avatar Tints — preview ao vivo do sprite com tint + barra de cor',
  'UI: Avatar Molduras — mini card decorativo com gradiente e indicador visual da cor',
  'UI: Avatar Fundos — preview do gradiente com padrão de estrelas',
  'Balance: Raids menos frequentes — intervalo de 2h→6h, gatilho de batalhas 50→200',
  'Fix: Pikachu adicionado à Floresta de Viridian com taxa canônica (~2%)',
  'Balance: Encontros com Pokémon iniciais agora são raros (~1%) nas rotas iniciais Kanto + regionais',
  'Feature: Receitas de Forja restauradas — drops progressivos nas rotas, TMs incluídas, guia de localização na UI',
  'Balance: Taxa de drop de receitas aumentada para rotas iniciais (9% lvl≤20 vs 5% geral); Pokébola agora dropa na Route 1',
  'UI: CraftingStation reformulada — mostra receitas bloqueadas com dica de onde farmar, badge ao desbloquear',
  'Fix: Raid sem Pokébolas — botão "Fechar" e "Recompensas" visíveis quando todas as bolas chegam a zero',
  'Fix: Ícones do Menu corrigidos — Pokédex 📕, Mochila 🎒 e Salvar 💾 agora usam emoji (100% confiável)',
  'Audit: Sistema de progressão entre regiões verificado — todas as 9 transições estão corretas',
  'Fix: Service Worker atualizado para v1.64.0 — cache antigo invalidado corretamente',
];
