export const APP_VERSION = '1.78.2';
export const VERSION = '1.78.2';
export const APP_VERSION_DATE = '13/05/2026 12:12';
export const CHANGELOG = [
  '## [V1.78.1] - 13/05/2026 12:02',
  '### Adicionado',
  '- **Sistema de Raids**:',
  '    - Adicionada chance de 0.5% de spawn imediato ao encontrar Pokémon selvagens nas rotas.',
  '    - Corrigido bug onde Raids expiradas bloqueavam o surgimento de novas.',
  '    - Reduzido tempo de spawn passivo para 1 hora.',
  '## [V1.78.0] - 13/05/2026 11:36',
  'UI: Redesign completo da tela de Raid com sprite centralizado e melhor legibilidade',
  'UI: Botões de ação da Raid agora possuem alto contraste (Branco/Preto) para melhor navegação',
  'System: Raids agora podem surgir aleatoriamente durante encontros nas rotas (0.5% de chance)',
  'Fix: Corrigida trava que impedia novas Raids se a anterior expirasse sem ser visualizada',
  'System: Intervalo de spawn automático de Raids reduzido de 6h para 1h',
  'System: Taxa de Pokémon Shiny padronizada para 1/4096 (escala progressiva por maestria)',
  'System: Gatilho de Raids ajustado para 50 batalhas (selvagens ou treinadores)',
  'Fix: Textos flutuantes (+HP, Buffs/Debuffs) agora aparecem sobre o Pokémon correto na batalha',
  'Fix: Duplicação de Pokémon em expedições resolvida (Pokémon agora permanecem no PC com status onExpedition)',
  'UI: Badge de status e travas de segurança adicionadas ao gerenciamento de Pokémon para expedições',
  'Fix: Notificações redundantes de receitas de forja resolvidas (correção de dependências de estado)',
  'Fix: Navegação do botão "CIDADE" corrigida para levar à Cidade em vez do Mapa',
  'Fix: Padronização total da taxa de spawn de todos os 27 Pokémon iniciais (Starters) para spawnWeight 10 (~1% chance)',
  'Fix: Implementação de trava de progresso para todos os starters: spawns agora exigem derrota do primeiro rival de sua região',
  'Fix: Iniciais de todas as 9 gerações — spawnWeight padronizado em 10 para ~1% de chance',
  'Fix: Encontros com iniciais em todas as regiões agora exigem a derrota do primeiro rival',
  'Fix: Iniciais de Johto/Hoenn/Sinnoh — spawnWeight aumentado de 2→10 para taxa de aparição equivalente a Kanto (~1%)',
  'Fix: Ícones de região (Johto/Hoenn/Alola/Paldea) trocados para sprites dos lendários via PokeAPI',
  'Fix: Ícone do título Rival trocado para scope-lens (blue-card era 404)',
  'Fix: Imagens do Pokémart/Forja — link_cable, poke_food, poke_food_premium agora usam PokeAPI',
  'UX: Seleção de título — delay de 200ms antes de fechar modal para mostrar badge Ativo',
  'Fix: Materiais de Forja agora dropam em todas as 9 regiões via TYPE_MATERIAL_MAP',
  'Feature: FORGE_MATERIAL_DROP_GUIDE expandido com 200+ novos Pokémon de todas as gerações',
  'Feature: Efeitos visuais de golpes — 120+ moves com animações únicas usando sprites do Pokémon Showdown (/fx/)',
  'Feature: Motor MoveAnimationLayer — 12 tipos de animação (projectile, burst, drain, quake, beam, slash, etc.)',
  'Feature: Fallback por tipo — todo golpe sem animação específica recebe visual baseado no seu tipo',
  'Feature: Efeitos secundários completos — Drain cura HP, Recoil dá dano próprio, Power-Up Punch/Flame Charge buffam stats, 6 tipos de chance de status em golpes de dano',
  'Release: V1.77.0 — Sistema completo de Held Items: 18 tipos + 4 especiais com efeitos de batalha',
  'Feature: TYPE_BOOSTS expandido para todos os 18 tipos (Silk Scarf, Miracle Seed, Never-Melt Ice, etc.)',
  'Feature: Life Orb — +30% dano + -8% HP de recuo por turno ao atacar',
  'Feature: Expert Belt — +20% dano adicional em golpes super efetivos',
  'Feature: Leftovers — recupera 5% HP por turno automaticamente',
  'Feature: Focus Sash — sobrevive a um golpe fatal com 1 HP (se HP era > 1)',
  'Feature: RECIPE_LABEL_OVERRIDES — dicas de localização para receitas de todos os held items',
  'Release: V1.76.9 consolidando Loja de Prestigio, Expedições e Minha Casa com cache publico atualizado',
  'Fix: Minha Casa — plantio agora respeita todos os slots disponiveis e consome sementes por canteiro',
  'Fix: Expedições — relatório de conclusão estabilizado, sem piscar e com botão de fechar funcionando',
  'UI: Expedições — recompensas agora exibem sprites de itens e Pokémon com fallbacks estáveis',
  'UX: Expedições — iniciar uma expedição mantém o jogador na área de expedições e respeita a duração escolhida',
  'UI: Loja de Prestigio refinada com abas tematicas, sprites Pokemon e fallbacks para icones quebrados',
  'UI: Estandartes de ginasio receberam icones de tipo e visual mais colecionavel',
  'Fix: Header, badges e moedas da Loja de Prestigio trocados para assets estaveis',
  'UX: Melhoria de Fluxo — adicionada confirmação de destino após batalhas de história (Rival/Equipes)',
  'UI: Ajustes Visuais — corrigido posicionamento da Loja de Prestígio, ícone da aba Ginásio e layout das insígnias',
  'Fix: Navegação da Forja — corrigido erro de redirecionamento que causava tela branca ao sair do modal de receita',
  'Feature: Raids Aprimoradas — gatilho de batalhas reduzido para 100 e nova arte de fundo épica para a tela de raid',
  'Feature: Sistema de Itens Segurados — agora é possível equipar itens forjados (Charcoal, Magnet, etc.) nos Pokémon para ganhar bônus de dano e efeitos especiais',
  'Fix: Imagens de Expedição — corrigido o caminho das imagens de fundo para compatibilidade com GitHub Pages',
  'UI: Loja de Prestígio — nova interface premium com ícones de pixel art e navegação otimizada para mobile',
  'Fix: Drop de Receitas — corrigido bug que permitia dropar receitas já conhecidas e disparar modal indevidamente',
  'Feature: Confirmação de EXP Candy — modal com prévia de XP antes/depois, badge de Level Up e botão Voltar',
  'Feature: Modal de Receita Encontrada — celebração visual com nome, ícone e efeito do item ao dropar receita',
  'Fix: Raid sem Pokébolas — botão "Fechar" e "Recompensas" visíveis quando todas as bolas chegam a zero',
  'Fix: Ícones do Menu corrigidos — Pokédex 📕, Mochila 🎒 e Salvar 💾 agora usam emoji (100% confiável)',
  'Fix: Avatar Leaf — sprite corrigido (leaf.png→green.png no PS, era 404)',
  'Fix: Avatar Florian/Juliana — sprites de Paldea corrigidos (florian→giacomo, juliana→penny)',
  'Fix: onError em todos os sprites de treinador — fallback para Red em vez de sumir',
  'UI: Modal de Expedição restaurado — ícones de itens (ITEM_LABELS), sprites dos Pokémon e visual completo',
  'Fix: Modal Galar→Paldea exibia Prof. Magnolia em vez de Prof. Sada (duplicate professor corrigido)',
  'Audit: Sistema de progressão entre regiões verificado — todas as 9 transições estão corretas',
  'Fix: Totodile em Johto — rota 30 corrigida (unlockLevel 61, req johto_route_29_cleared, requiresFlag no Totodile)',
  'Fix: Auditoria completa de iniciais — todos os 26 Pokémon iniciais confirmados em todas as 9 regiões',
  'Fix: Pikachu em Viridian Forest — adicionado forceSpawn para bypass do filtro de evoluídos em rotas lvl≤15',
  'Fix: Iniciais pós-rival — Kanto/Johto/Hoenn/Sinnoh agora exigem derrota do rival (requiresFlag)',
  'Fix: Iniciais geração 5-9 — formas base corretas (Snivy/Tepig/Oshawott etc.) em vez de evoluções finais',
  'Balance: Distribuição corrigida — máx 2 iniciais por rota, 3º inicial na rota intermediária (forma base)',
  'Fix: buildRegionRoutes — starters removidos da route_1; starterBases usados nas rotas iniciais extras',
  'Balance: Economia drasticamente rebalanceada — coins por Pokémon selvagem 10x mais difícil (level×0.15)',
  'Balance: Recompensa de treinadores reduzida em 80% (multiplicador 0.20 aplicado globalmente)',
  'Balance: Encounters iniciais corrigidos — máx 2 iniciais por rota, distribuídos em todas as gerações',
  'Kanto: Rota 1 → Bulbasaur+Charmander | Rota 22 → Squirtle+Eevee | Viridian Forest → Pikachu (pós rival)',
  'Johto: Rota 29 → Chikorita+Cyndaquil | Rota 30 → Totodile (pós rival)',
  'Hoenn: Rota 101 → Treecko+Torchic | Rota 102 → Mudkip',
  'Sinnoh: Rota 201 → Turtwig+Chimchar | Rota 202 → Piplup',
  'Unova/Kalos/Alola/Galar/Paldea: inicial[0]+[1] na rota 1, inicial[2] na rota inicial secundária',
  'Fix: Loja de Prestígio — tela azul ao acessar aba Avatar corrigida (hook fora de IIFE)',
  'UI: Avatar — card de preview ao vivo com glow dinâmico da moldura e gradiente do fundo',
  'UI: Avatar Sprites — agrupados por região com cabeçalhos, grid 3 colunas, overlay de bloqueio',
  'UI: Avatar Tints — preview ao vivo do sprite com tint + barra de cor',
  'UI: Avatar Molduras — mini card decorativo com gradiente e indicador visual da cor',
  'UI: Avatar Fundos — preview do gradiente com padrão de estrelas',
  'Balance: Raids menos frequentes — intervalo de 2h→6h, gatilho de batalhas 50→200',
  'Fix: Pikachu adicionado à Floresta de Viridian com taxa canônica (~2%)',
  'Balance: Encontros com Pokémon iniciais agora são raros (~1%) nas rotas iniciais Kanto + regionais',
  'Feature: Receitas de Forja restauradas — drops progressivos nas rotas, TMs incluídas, guia de localização na UI',
  'Balance: Taxa de drop de receitas aumentada para rotas iniciais (9% lvl≤20 vs 5% geral); Pokébola agora dropa na Route 1',
  'UI: CraftingStation reformulada — mostra receitas bloqueadas com dica de onde farmar, badge ao desbloquear',
  'Fix: Raid duplicata → EXP Candy — capturar espécie já existente gera EXP Candy proporcional às estrelas (XS→XL)',
  'Feature: EXP Candies — 5 tamanhos (XS/S/M/L/XL) drop de raids, armazenadas na Mochila, aplicáveis a qualquer Pokémon',
  'UI: Mochila → aba EXP Candy com modal de seleção de Pokémon — mostra XP atual, barra de progresso e preview do ganho',
  'Feature: Sistema de Avatar — sprites por região, tints de cor, molduras e fundos personalizáveis na Loja de Prestígio',
  'Feature: Desbloqueio Progressivo de Avatar — cosméticos gratuitos ao vencer campeões regionais, premium na loja',
  'Balance: Raids Progressivas — estrelas limitadas por insígnias (0-1→1★, 2-3→2★, 4-5→3★, 6-7→4★, 8+→5★)',
  'Fix: Sincronização de Save — redirecionamento automático para a cidade ao detectar progresso na nuvem',
  'Hotfix: Resolvido erro de monitorAuthState indefinido que causava tela azul no carregamento',
  'Feature: Modal de Vitória Unificado — novos visuais e fluxos para Ginásios, Elite Four, Rivais e Equipes Vilãs',
  'Fix: Acesso Regional — validateTeamAccess agora permite Pokémon capturados na região ativa, independente da geração',
  'Fix: Estabilidade de PC — refatoração de moveToPC para usar instanceId, eliminando bugs de dessincronização de índice',
  'Fix: Service Worker atualizado para v1.64.0 — cache antigo invalidado corretamente',
  'Fix: Import morto de onAuthStateChanged removido do AppRoot (redução de bundle)',
  'Fix: Bioma Pradaria (Safari Zone) com ícone correto 🌿 em vez de 🌊',
  'Fix: selectedStarters agora salvo corretamente em Johto, Hoenn e Sinnoh (consistência com Gen 5+)',
  'Fix: Auditoria v1.63.0 — estabilização de rotas iniciais (Unova) e carregamento de saves',
  'Fix: Race Condition — unificação dos listeners de autenticação e sincronização cloud',
  'Feature: Estabilização de Alola — refatoração dos Trial Captains e remoção de duplicatas na Liga',
  'Balance: Bônus de Prestígio — multiplicadores de XP em temas e bônus de cuidador acumulativo (3x cap)',
  'UI: Consistência de Itens — correção de ícones (Sitrus Berry/Apricorns) e rótulos faltantes',
];
