export const APP_VERSION = '1.71.0';
export const VERSION = '1.71.0';
export const APP_VERSION_DATE = '12/05/2026 23:30';
export const CHANGELOG = [
  'Fix: Loja de Prestígio — tela azul ao acessar aba Avatar corrigida (hook fora de IIFE)',
  'UI: Avatar — card de preview ao vivo com glow dinâmico da moldura e gradiente do fundo',
  'UI: Avatar Sprites — agrupados por região com cabeçalhos, grid 3 colunas, overlay de bloqueio',
  'UI: Avatar Tints — preview ao vivo do sprite com tint + barra de cor',
  'UI: Avatar Molduras — mini card decorativo com gradiente e indicador visual da cor',
  'UI: Avatar Fundos — preview do gradiente com padrão de estrelas',
  'Balance: Raids menos frequentes — intervalo de 2h→6h, gatilho de batalhas 50→200',
  'Fix: Pikachu adicionado à Floresta de Viridian com taxa canônica (~2%)',
  'Balance: Encontros com Pokémon iniciais agora são raros (~1%) nas rotas iniciais Kanto + regionais',
  'Feature: Receitas de Forja restauradas — drops progressivos nas rotas, TMs incluídas, guia de localização na UI',
  'Balance: Taxa de drop de receitas aumentada para rotas iniciais (9% lvl≤20 vs 5% geral); Pokébola agora dropa na Route 1',
  'UI: CraftingStation reformulada — mostra receitas bloqueadas com dica de onde farmar, badge ao desbloquear',
  'Fix: Raid duplicata → EXP Candy — capturar espécie já existente gera EXP Candy proporcional às estrelas (XS→XL)',
  'Feature: EXP Candies — 5 tamanhos (XS/S/M/L/XL) drop de raids, armazenadas na Mochila, aplicáveis a qualquer Pokémon',
  'UI: Mochila → aba EXP Candy com modal de seleção de Pokémon — mostra XP atual, barra de progresso e preview do ganho',
  'Feature: Sistema de Avatar — sprites por região, tints de cor, molduras e fundos personalizáveis na Loja de Prestígio',
  'Feature: Desbloqueio Progressivo de Avatar — cosméticos gratuitos ao vencer campeões regionais, premium na loja',
  'Balance: Raids Progressivas — estrelas limitadas por insígnias (0-1→1★, 2-3→2★, 4-5→3★, 6-7→4★, 8+→5★)',
  'Fix: Sincronização de Save — redirecionamento automático para a cidade ao detectar progresso na nuvem',
  'Hotfix: Resolvido erro de monitorAuthState indefinido que causava tela azul no carregamento',
  'Feature: Modal de Vitória Unificado — novos visuais e fluxos para Ginásios, Elite Four, Rivais e Equipes Vilãs',
  'Fix: Acesso Regional — validateTeamAccess agora permite Pokémon capturados na região ativa, independente da geração',
  'Fix: Estabilidade de PC — refatoração de moveToPC para usar instanceId, eliminando bugs de dessincronização de índice',
  'Fix: Service Worker atualizado para v1.64.0 — cache antigo invalidado corretamente',
  'Fix: Import morto de onAuthStateChanged removido do AppRoot (redução de bundle)',
  'Fix: Bioma Pradaria (Safari Zone) com ícone correto 🌿 em vez de 🌊',
  'Fix: selectedStarters agora salvo corretamente em Johto, Hoenn e Sinnoh (consistência com Gen 5+)',
  'Fix: Auditoria v1.63.0 — estabilização de rotas iniciais (Unova) e carregamento de saves',
  'Fix: Race Condition — unificação dos listeners de autenticação e sincronização cloud',
  'Feature: Estabilização de Alola — refatoração dos Trial Captains e remoção de duplicatas na Liga',
  'Balance: Bônus de Prestígio — multiplicadores de XP em temas e bônus de cuidador acumulativo (3x cap)',
  'UI: Consistência de Itens — correção de ícones (Sitrus Berry/Apricorns) e rótulos faltantes',
];
