const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'ChallengesScreen.jsx');
let content = fs.readFileSync(filePath, 'utf8');

// 1. Sinnoh challenges to add
const sinnohChallenges = `  {
    region: 'sinnoh',
    id: 'sinnoh_roark',
    category: 'sinnoh',
    name: 'Roark',
    subtitle: 'Lider de Oreburgh',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/roark.png',
    quote: '"Minha paixao por fosseis e escavacao nao tem limites!"',
    reward: 20000,
    unlockFlag: 'coal_badge',
    requiresFlag: 'sinnoh_started',
    team: [
      { id: 74, level: 12 },
      { id: 95, level: 12 },
      { id: 408, level: 14 },
    ],
    background: "url('/bg_oreburgh.png') center/cover no-repeat",
    location: 'Ginasio de Oreburgh',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_gardenia',
    category: 'sinnoh',
    name: 'Gardenia',
    subtitle: 'Lider de Eterna',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/gardenia.png',
    quote: '"As plantas sao lindas, mas tambem podem ser perigosas!"',
    reward: 25000,
    unlockFlag: 'forest_badge',
    requiresFlag: 'coal_badge',
    team: [
      { id: 420, level: 20 },
      { id: 387, level: 20 },
      { id: 407, level: 22 },
    ],
    background: "url('/bg_eterna.png') center/cover no-repeat",
    location: 'Ginasio de Eterna',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_maylene',
    category: 'sinnoh',
    name: 'Maylene',
    subtitle: 'Lider de Veilstone',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/maylene.png',
    quote: '"Eu luto ao lado dos meus Pokemons com todo o meu coracao!"',
    reward: 30000,
    unlockFlag: 'cobble_badge',
    requiresFlag: 'forest_badge',
    team: [
      { id: 307, level: 28 },
      { id: 67, level: 28 },
      { id: 448, level: 32 },
    ],
    background: "url('/bg_jubilife.png') center/cover no-repeat",
    location: 'Ginasio de Veilstone',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_wake',
    category: 'sinnoh',
    name: 'Crasher Wake',
    subtitle: 'Lider de Pastoria',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/crasherwake.png',
    quote: '"Prepare-se para ser varrido pela mare!"',
    reward: 35000,
    unlockFlag: 'fen_badge',
    requiresFlag: 'cobble_badge',
    team: [
      { id: 130, level: 34 },
      { id: 419, level: 34 },
      { id: 195, level: 37 },
    ],
    background: "url('/bg_pastoria.png') center/cover no-repeat",
    location: 'Ginasio de Pastoria',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_fantina',
    category: 'sinnoh',
    name: 'Fantina',
    subtitle: 'Lider de Hearthome',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/fantina.png',
    quote: '"A danca e a batalha sao uma so arte!"',
    reward: 40000,
    unlockFlag: 'relic_badge',
    requiresFlag: 'fen_badge',
    team: [
      { id: 426, level: 32 },
      { id: 93, level: 34 },
      { id: 429, level: 36 },
    ],
    background: "url('/bg_hearthome.png') center/cover no-repeat",
    location: 'Ginasio de Hearthome',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_byron',
    category: 'sinnoh',
    name: 'Byron',
    subtitle: 'Lider de Canalave',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/byron.png',
    quote: '"Minha defesa e tao dura quanto o aco!"',
    reward: 45000,
    unlockFlag: 'mine_badge',
    requiresFlag: 'relic_badge',
    team: [
      { id: 437, level: 37 },
      { id: 95, level: 38 },
      { id: 411, level: 41 },
    ],
    background: "url('/bg_canalave.png') center/cover no-repeat",
    location: 'Ginasio de Canalave',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_candice',
    category: 'sinnoh',
    name: 'Candice',
    subtitle: 'Lider de Snowpoint',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/candice.png',
    quote: '"O gelo e frio, mas minha paixao queima!"',
    reward: 50000,
    unlockFlag: 'icicle_badge',
    requiresFlag: 'mine_badge',
    team: [
      { id: 215, level: 40 },
      { id: 460, level: 42 },
      { id: 124, level: 44 },
      { id: 478, level: 44 },
    ],
    background: "url('/bg_snowpoint.png') center/cover no-repeat",
    location: 'Ginasio de Snowpoint',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_volkner',
    category: 'sinnoh',
    name: 'Volkner',
    subtitle: 'Lider de Sunyshore',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/volkner.png',
    quote: '"Espero que voce possa iluminar minha vida de novo!"',
    reward: 60000,
    unlockFlag: 'beacon_badge',
    requiresFlag: 'icicle_badge',
    team: [
      { id: 405, level: 46 },
      { id: 125, level: 46 },
      { id: 135, level: 48 },
      { id: 466, level: 50 },
    ],
    background: "url('/bg_sunyshore.png') center/cover no-repeat",
    location: 'Ginasio de Sunyshore',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_aaron',
    category: 'sinnoh',
    name: 'Aaron',
    subtitle: 'Elite Four - Inseto',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/aaron.png',
    quote: '"Meus insetos vao te picar com força!"',
    reward: 80000,
    unlockFlag: 'sinnoh_aaron_defeated',
    requiresFlag: 'beacon_badge',
    team: [
      { id: 469, level: 53 },
      { id: 212, level: 54 },
      { id: 214, level: 54 },
      { id: 416, level: 54 },
      { id: 452, level: 57 },
    ],
    background: "url('/bg_sinnoh_league.png') center/cover no-repeat",
    location: 'Liga Pokémon de Sinnoh',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_bertha',
    category: 'sinnoh',
    name: 'Bertha',
    subtitle: 'Elite Four - Terra',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/bertha.png',
    quote: '"A terra e sabia e implacavel."',
    reward: 85000,
    unlockFlag: 'sinnoh_bertha_defeated',
    requiresFlag: 'sinnoh_aaron_defeated',
    team: [
      { id: 464, level: 55 },
      { id: 340, level: 56 },
      { id: 450, level: 56 },
      { id: 472, level: 58 },
      { id: 452, level: 59 },
    ],
    background: "url('/bg_sinnoh_league.png') center/cover no-repeat",
    location: 'Liga Pokémon de Sinnoh',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_flint',
    category: 'sinnoh',
    name: 'Flint',
    subtitle: 'Elite Four - Fogo',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/flint.png',
    quote: '"Sinta o calor da batalha!"',
    reward: 90000,
    unlockFlag: 'sinnoh_flint_defeated',
    requiresFlag: 'sinnoh_bertha_defeated',
    team: [
      { id: 78, level: 58 },
      { id: 428, level: 57 },
      { id: 126, level: 58 },
      { id: 392, level: 61 },
      { id: 467, level: 59 },
    ],
    background: "url('/bg_sinnoh_league.png') center/cover no-repeat",
    location: 'Liga Pokémon de Sinnoh',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_lucian',
    category: 'sinnoh',
    name: 'Lucian',
    subtitle: 'Elite Four - Psiquico',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/lucian.png',
    quote: '"Sua mente e um livro aberto para mim."',
    reward: 95000,
    unlockFlag: 'sinnoh_lucian_defeated',
    requiresFlag: 'sinnoh_flint_defeated',
    team: [
      { id: 122, level: 59 },
      { id: 196, level: 59 },
      { id: 65, level: 60 },
      { id: 437, level: 63 },
      { id: 475, level: 63 },
    ],
    background: "url('/bg_sinnoh_league.png') center/cover no-repeat",
    location: 'Liga Pokémon de Sinnoh',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_champion_cynthia',
    category: 'sinnoh',
    name: 'Cynthia',
    subtitle: 'Campeã de Sinnoh',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/cynthia.png',
    quote: '"Eu quero saber o quao forte voce e. Mostre-me!"',
    reward: 200000,
    unlockFlag: 'sinnoh_champion',
    requiresFlag: 'sinnoh_lucian_defeated',
    team: [
      { id: 442, level: 61 },
      { id: 407, level: 60 },
      { id: 445, level: 66 },
      { id: 448, level: 63 },
      { id: 350, level: 63 },
      { id: 423, level: 60 },
    ],
    background: "url('/bg_sinnoh_league.png') center/cover no-repeat",
    location: 'Santuário da Liga Pokémon',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_mars',
    category: 'rocket',
    name: 'Mars',
    subtitle: 'Comandante Galactic',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/mars.png',
    quote: '"Voce esta no caminho do novo mundo!"',
    reward: 15000,
    unlockFlag: 'sinnoh_mars_defeated',
    requiresFlag: 'sinnoh_started',
    team: [
      { id: 41, level: 14 },
      { id: 432, level: 16 },
    ],
    background: "url('/bg_pastoria.png') center/cover no-repeat",
    location: 'Valley Windworks',
  },
  {
    region: 'sinnoh',
    id: 'sinnoh_cyrus',
    category: 'rocket',
    name: 'Cyrus',
    subtitle: 'Lider da Equipe Galactic',
    sprite: 'https://play.pokemonshowdown.com/sprites/trainers/cyrus.png',
    quote: '"As emocoes sao inuteis. Criarei um mundo perfeito!"',
    reward: 100000,
    unlockFlag: 'sinnoh_cyrus_defeated',
    requiresFlag: 'mine_badge',
    team: [
      { id: 198, level: 45 },
      { id: 215, level: 46 },
      { id: 169, level: 46 },
      { id: 430, level: 48 },
    ],
    background: "url('/bg_spear_pillar.png') center/cover no-repeat",
    location: 'Spear Pillar',
  },
];`;

const insertIndex = content.lastIndexOf('];', content.indexOf('const CATEGORY_CONFIG'));
if (insertIndex !== -1) {
    const before = content.substring(0, insertIndex);
    const after = content.substring(insertIndex);
    content = before + ',\n' + sinnohChallenges + '\n' + after;
}

fs.writeFileSync(filePath, content);
console.log('Successfully merged Sinnoh challenges!');
